/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pcstore.view;

import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

import com.pcstore.controller.CustomerController;
import com.pcstore.utils.TableStyleUtil;

/**
 *
 * @author MSII
 */
public class CustomerForm extends javax.swing.JPanel {


    private TableRowSorter<TableModel> tableListCustomerSorter;
    private CustomerController customerController;

    /**
     * Creates new form Customer
     */
    public CustomerForm() {
        initComponents();
        setupCusmizeTable();
        customerController = new CustomerController(this);  
        labelESC.setVisible(false);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        lableTitle = new javax.swing.JLabel();
        panelAction = new javax.swing.JPanel();
        btnAddCustomer = new com.k33ptoo.components.KButton();
        btnUpdate = new com.k33ptoo.components.KButton();
        btnDeleteCustomer = new com.k33ptoo.components.KButton();
        btnRefresh = new com.k33ptoo.components.KButton();
        panelExport = new javax.swing.JPanel();
        btnExportExcel = new javax.swing.JButton();
        panelInfoDetail = new javax.swing.JPanel();
        panelCustomerID = new javax.swing.JPanel();
        labelCustomerID = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        panelCustomerPhone = new javax.swing.JPanel();
        labelCustmerPhone = new javax.swing.JLabel();
        txtCustomerPhone = new javax.swing.JTextField();
        panelCreateUpdate = new javax.swing.JPanel();
        labeCreateUpdate = new javax.swing.JLabel();
        txtCreateUpdate = new javax.swing.JTextField();
        panelCustomerName = new javax.swing.JPanel();
        labelCustomerName = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        panelCustomerEmail = new javax.swing.JPanel();
        labelCustomerEmail = new javax.swing.JLabel();
        txtCustomerEmail = new javax.swing.JTextField();
        panelCreateAt = new javax.swing.JPanel();
        labelCreateAt = new javax.swing.JLabel();
        txtCreateAt = new javax.swing.JTextField();
        panelCustomerGender = new javax.swing.JPanel();
        labelCustomerGender = new javax.swing.JLabel();
        txtCustomerGender = new javax.swing.JTextField();
        panelCustomerPoint = new javax.swing.JPanel();
        labelCustomerPoint = new javax.swing.JLabel();
        txtCustomerPoint = new javax.swing.JTextField();
        panelEmpty = new javax.swing.JPanel();
        labelESC = new javax.swing.JLabel();
        panelSort = new javax.swing.JPanel();
        textFieldSearch = new com.pcstore.utils.TextFieldSearch();
        labelSort = new javax.swing.JLabel();
        cbbSortCustomer = new javax.swing.JComboBox<>();
        cbbSort = new javax.swing.JComboBox<>();
        btnResetSort = new javax.swing.JButton();
        panelListCustomer = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        tableCustomers = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1197, 713));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        panelHeader.setOpaque(false);
        panelHeader.setPreferredSize(new java.awt.Dimension(100, 40));
        panelHeader.setLayout(new java.awt.BorderLayout());

        lableTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lableTitle.setForeground(new java.awt.Color(0, 51, 204));
        lableTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/pcstore/resources/vi_VN"); // NOI18N
        lableTitle.setText(bundle.getString("lbMenuCustomer")); // NOI18N
        panelHeader.add(lableTitle, java.awt.BorderLayout.CENTER);

        add(panelHeader);

        panelAction.setOpaque(false);
        panelAction.setPreferredSize(new java.awt.Dimension(1197, 60));
        panelAction.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnAddCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/user-add_2.png"))); // NOI18N
        btnAddCustomer.setText(bundle.getString("btnAddCustomer")); // NOI18N
        btnAddCustomer.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnAddCustomer.setIconTextGap(15);
        btnAddCustomer.setkBorderRadius(30);
        btnAddCustomer.setkEndColor(new java.awt.Color(0, 255, 51));
        btnAddCustomer.setkHoverEndColor(new java.awt.Color(0, 204, 255));
        btnAddCustomer.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnAddCustomer.setkHoverStartColor(new java.awt.Color(0, 204, 255));
        btnAddCustomer.setkStartColor(new java.awt.Color(0, 204, 255));
        btnAddCustomer.setPreferredSize(new java.awt.Dimension(185, 35));
        panelAction.add(btnAddCustomer);

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/user-pen.png"))); // NOI18N
        btnUpdate.setText(bundle.getString("btnUpdate")); // NOI18N
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnUpdate.setIconTextGap(15);
        btnUpdate.setkBorderRadius(30);
        btnUpdate.setkEndColor(new java.awt.Color(0, 153, 153));
        btnUpdate.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnUpdate.setkHoverStartColor(new java.awt.Color(102, 102, 255));
        btnUpdate.setPreferredSize(new java.awt.Dimension(185, 35));
        panelAction.add(btnUpdate);

        btnDeleteCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/trash.png"))); // NOI18N
        btnDeleteCustomer.setText(bundle.getString("btnDeleteCustomer")); // NOI18N
        btnDeleteCustomer.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnDeleteCustomer.setIconTextGap(15);
        btnDeleteCustomer.setkBorderRadius(30);
        btnDeleteCustomer.setkEndColor(new java.awt.Color(255, 102, 51));
        btnDeleteCustomer.setkHoverEndColor(new java.awt.Color(255, 0, 51));
        btnDeleteCustomer.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDeleteCustomer.setkHoverStartColor(new java.awt.Color(255, 102, 0));
        btnDeleteCustomer.setkStartColor(new java.awt.Color(255, 0, 51));
        btnDeleteCustomer.setLabel(bundle.getString("btnDeleteCustomer")); // NOI18N
        btnDeleteCustomer.setPreferredSize(new java.awt.Dimension(185, 35));
        btnDeleteCustomer.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/trash.png"))); // NOI18N
        panelAction.add(btnDeleteCustomer);

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/refresh.png"))); // NOI18N
        btnRefresh.setText(bundle.getString("btnRefresh")); // NOI18N
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnRefresh.setIconTextGap(20);
        btnRefresh.setkBorderRadius(30);
        btnRefresh.setkEndColor(new java.awt.Color(153, 204, 255));
        btnRefresh.setkHoverEndColor(new java.awt.Color(102, 204, 255));
        btnRefresh.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnRefresh.setkHoverStartColor(new java.awt.Color(102, 204, 255));
        btnRefresh.setkStartColor(new java.awt.Color(153, 204, 255));
        btnRefresh.setPreferredSize(new java.awt.Dimension(185, 35));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        panelAction.add(btnRefresh);

        panelExport.setBackground(new java.awt.Color(255, 255, 255));
        panelExport.setOpaque(false);
        panelExport.setPreferredSize(new java.awt.Dimension(350, 35));
        panelExport.setLayout(new java.awt.BorderLayout());

        btnExportExcel.setBackground(new java.awt.Color(30, 113, 69));
        btnExportExcel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExportExcel.setForeground(new java.awt.Color(255, 255, 255));
        btnExportExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/excel.png"))); // NOI18N
        btnExportExcel.setText(bundle.getString("btnExportExcel")); // NOI18N
        btnExportExcel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportExcelActionPerformed(evt);
            }
        });
        panelExport.add(btnExportExcel, java.awt.BorderLayout.EAST);

        panelAction.add(panelExport);

        add(panelAction);

        panelInfoDetail.setBackground(new java.awt.Color(255, 255, 255));
        panelInfoDetail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("txtDetails"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        panelInfoDetail.setPreferredSize(new java.awt.Dimension(400, 200));
        panelInfoDetail.setLayout(new java.awt.GridLayout(4, 3, 30, 23));

        panelCustomerID.setOpaque(false);
        panelCustomerID.setLayout(new java.awt.BorderLayout(15, 0));

        labelCustomerID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCustomerID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCustomerID.setText(bundle.getString("txtCustomerID")); // NOI18N
        labelCustomerID.setPreferredSize(new java.awt.Dimension(120, 16));
        panelCustomerID.add(labelCustomerID, java.awt.BorderLayout.LINE_START);

        txtCustomerID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCustomerID.setBorder(null);
        txtCustomerID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCustomerID.setEnabled(false);
        txtCustomerID.setOpaque(true);
        txtCustomerID.setPreferredSize(new java.awt.Dimension(100, 2));
        panelCustomerID.add(txtCustomerID, java.awt.BorderLayout.CENTER);

        panelInfoDetail.add(panelCustomerID);

        panelCustomerPhone.setOpaque(false);
        panelCustomerPhone.setLayout(new java.awt.BorderLayout(15, 0));

        labelCustmerPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCustmerPhone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCustmerPhone.setText(bundle.getString("lbPhoneNumber")); // NOI18N
        labelCustmerPhone.setPreferredSize(new java.awt.Dimension(120, 16));
        panelCustomerPhone.add(labelCustmerPhone, java.awt.BorderLayout.LINE_START);

        txtCustomerPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCustomerPhone.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCustomerPhone.setOpaque(true);
        txtCustomerPhone.setPreferredSize(new java.awt.Dimension(100, 2));
        panelCustomerPhone.add(txtCustomerPhone, java.awt.BorderLayout.CENTER);

        panelInfoDetail.add(panelCustomerPhone);

        panelCreateUpdate.setOpaque(false);
        panelCreateUpdate.setLayout(new java.awt.BorderLayout(15, 0));

        labeCreateUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labeCreateUpdate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labeCreateUpdate.setText(bundle.getString("lbCreateUpdate")); // NOI18N
        labeCreateUpdate.setPreferredSize(new java.awt.Dimension(120, 16));
        panelCreateUpdate.add(labeCreateUpdate, java.awt.BorderLayout.LINE_START);

        txtCreateUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCreateUpdate.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCreateUpdate.setOpaque(true);
        txtCreateUpdate.setPreferredSize(new java.awt.Dimension(100, 2));
        panelCreateUpdate.add(txtCreateUpdate, java.awt.BorderLayout.CENTER);

        panelInfoDetail.add(panelCreateUpdate);

        panelCustomerName.setOpaque(false);
        panelCustomerName.setLayout(new java.awt.BorderLayout(15, 0));

        labelCustomerName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCustomerName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCustomerName.setText(bundle.getString("lbName")); // NOI18N
        labelCustomerName.setPreferredSize(new java.awt.Dimension(120, 16));
        panelCustomerName.add(labelCustomerName, java.awt.BorderLayout.LINE_START);

        txtCustomerName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCustomerName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCustomerName.setOpaque(true);
        txtCustomerName.setPreferredSize(new java.awt.Dimension(100, 2));
        panelCustomerName.add(txtCustomerName, java.awt.BorderLayout.CENTER);

        panelInfoDetail.add(panelCustomerName);

        panelCustomerEmail.setOpaque(false);
        panelCustomerEmail.setLayout(new java.awt.BorderLayout(15, 0));

        labelCustomerEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCustomerEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCustomerEmail.setText(bundle.getString("lbEmail")); // NOI18N
        labelCustomerEmail.setPreferredSize(new java.awt.Dimension(120, 16));
        panelCustomerEmail.add(labelCustomerEmail, java.awt.BorderLayout.LINE_START);

        txtCustomerEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCustomerEmail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCustomerEmail.setOpaque(true);
        txtCustomerEmail.setPreferredSize(new java.awt.Dimension(100, 2));
        panelCustomerEmail.add(txtCustomerEmail, java.awt.BorderLayout.CENTER);

        panelInfoDetail.add(panelCustomerEmail);

        panelCreateAt.setOpaque(false);
        panelCreateAt.setLayout(new java.awt.BorderLayout(15, 0));

        labelCreateAt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCreateAt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCreateAt.setText(bundle.getString("lbCreateAt")); // NOI18N
        labelCreateAt.setPreferredSize(new java.awt.Dimension(120, 16));
        panelCreateAt.add(labelCreateAt, java.awt.BorderLayout.LINE_START);

        txtCreateAt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCreateAt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCreateAt.setOpaque(true);
        txtCreateAt.setPreferredSize(new java.awt.Dimension(100, 2));
        panelCreateAt.add(txtCreateAt, java.awt.BorderLayout.CENTER);

        panelInfoDetail.add(panelCreateAt);

        panelCustomerGender.setOpaque(false);
        panelCustomerGender.setLayout(new java.awt.BorderLayout(15, 0));

        labelCustomerGender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCustomerGender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCustomerGender.setText(bundle.getString("lbGender")); // NOI18N
        labelCustomerGender.setPreferredSize(new java.awt.Dimension(120, 16));
        panelCustomerGender.add(labelCustomerGender, java.awt.BorderLayout.LINE_START);

        txtCustomerGender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCustomerGender.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCustomerGender.setOpaque(true);
        txtCustomerGender.setPreferredSize(new java.awt.Dimension(100, 2));
        panelCustomerGender.add(txtCustomerGender, java.awt.BorderLayout.CENTER);

        panelInfoDetail.add(panelCustomerGender);

        panelCustomerPoint.setOpaque(false);
        panelCustomerPoint.setLayout(new java.awt.BorderLayout(15, 0));

        labelCustomerPoint.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCustomerPoint.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCustomerPoint.setText(bundle.getString("lbPoint")); // NOI18N
        labelCustomerPoint.setPreferredSize(new java.awt.Dimension(120, 16));
        panelCustomerPoint.add(labelCustomerPoint, java.awt.BorderLayout.LINE_START);

        txtCustomerPoint.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCustomerPoint.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCustomerPoint.setOpaque(true);
        txtCustomerPoint.setPreferredSize(new java.awt.Dimension(100, 2));
        panelCustomerPoint.add(txtCustomerPoint, java.awt.BorderLayout.CENTER);

        panelInfoDetail.add(panelCustomerPoint);

        panelEmpty.setOpaque(false);
        panelEmpty.setLayout(new java.awt.BorderLayout(15, 0));

        labelESC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelESC.setForeground(new java.awt.Color(255, 0, 51));
        labelESC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/exclamation.png"))); // NOI18N
        labelESC.setText(bundle.getString("labelNoteESC")); // NOI18N
        panelEmpty.add(labelESC, java.awt.BorderLayout.PAGE_END);

        panelInfoDetail.add(panelEmpty);

        add(panelInfoDetail);

        panelSort.setBackground(new java.awt.Color(255, 255, 255));
        panelSort.setPreferredSize(new java.awt.Dimension(1197, 70));
        panelSort.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 20));

        textFieldSearch.setPreferredSize(new java.awt.Dimension(450, 31));
        panelSort.add(textFieldSearch);

        labelSort.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelSort.setText(bundle.getString("lbSort")); // NOI18N
        panelSort.add(labelSort);

        cbbSortCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Không>", "Tên khách hàng", "Điểm" }));
        cbbSortCustomer.setPreferredSize(new java.awt.Dimension(150, 30));
        panelSort.add(cbbSortCustomer);

        cbbSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Không>", "Tăng dần", "Giảm giần" }));
        cbbSort.setPreferredSize(new java.awt.Dimension(100, 30));
        panelSort.add(cbbSort);

        btnResetSort.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/refresh.png"))); // NOI18N
        btnResetSort.setPreferredSize(new java.awt.Dimension(50, 25));
        btnResetSort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetSortMouseClicked(evt);
            }
        });
        panelSort.add(btnResetSort);

        add(panelSort);

        panelListCustomer.setBackground(new java.awt.Color(255, 255, 255));
        panelListCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), bundle.getString("txtListCustomer"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        panelListCustomer.setMinimumSize(new java.awt.Dimension(1197, 200));
        panelListCustomer.setOpaque(false);
        panelListCustomer.setPreferredSize(new java.awt.Dimension(1197, 400));
        panelListCustomer.setLayout(new java.awt.BorderLayout());

        scrollPane.setMinimumSize(new java.awt.Dimension(1197, 200));
        scrollPane.setName(""); // NOI18N
        scrollPane.setViewportView(tableCustomers);

        tableCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Số diện thoại", "Email", "Tích điểm", "Thời gian tạo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCustomers.setMinimumSize(new java.awt.Dimension(1197, 400));
        tableCustomers.getTableHeader().setReorderingAllowed(false);
        scrollPane.setViewportView(tableCustomers);
        if (tableCustomers.getColumnModel().getColumnCount() > 0) {
            tableCustomers.getColumnModel().getColumn(0).setPreferredWidth(10);
            tableCustomers.getColumnModel().getColumn(1).setPreferredWidth(30);
            tableCustomers.getColumnModel().getColumn(2).setPreferredWidth(10);
            tableCustomers.getColumnModel().getColumn(3).setPreferredWidth(20);
            tableCustomers.getColumnModel().getColumn(5).setPreferredWidth(20);
        }

        panelListCustomer.add(scrollPane, java.awt.BorderLayout.CENTER);

        add(panelListCustomer);
    }// </editor-fold>//GEN-END:initComponents


    private void setupCusmizeTable(){
        tableListCustomerSorter = TableStyleUtil.applyDefaultStyle(tableCustomers);

        //Thiết lập kích thước cột

    }

    private void btnExportExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportExcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportExcelActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnResetSortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetSortMouseClicked
        cbbSortCustomer.setSelectedIndex(0);
        cbbSort.setSelectedIndex(0);
    }//GEN-LAST:event_btnResetSortMouseClicked

    
    public TableRowSorter<TableModel> getTableListCustomerSorter() {
        return tableListCustomerSorter;
    }

    public com.k33ptoo.components.KButton getBtnAddCustomer() {
        return btnAddCustomer;
    }

    public com.k33ptoo.components.KButton getBtnDeleteCustomer() {
        return btnDeleteCustomer;
    }

    public javax.swing.JButton getBtnExportExcel() {
        return btnExportExcel;
    }

    public com.k33ptoo.components.KButton getBtnRefresh() {
        return btnRefresh;
    }

    public javax.swing.JButton getBtnResetSort() {
        return btnResetSort;
    }

    public com.k33ptoo.components.KButton getBtnUpdate() {
        return btnUpdate;
    }

    public javax.swing.JComboBox<String> getCbbSort() {
        return cbbSort;
    }

    public javax.swing.JComboBox<String> getCbbSortCustomer() {
        return cbbSortCustomer;
    }

    public javax.swing.JTable getTableCustomers() {
        return tableCustomers;
    }

    public com.pcstore.utils.TextFieldSearch getTextFieldSearch() {
        return textFieldSearch;
    }

    public javax.swing.JTextField getTxtCreateAt() {
        return txtCreateAt;
    }

    public javax.swing.JTextField getTxtCreateUpdate() {
        return txtCreateUpdate;
    }

    public javax.swing.JTextField getTxtCustomerEmail() {
        return txtCustomerEmail;
    }

    public javax.swing.JTextField getTxtCustomerGender() {
        return txtCustomerGender;
    }

    public javax.swing.JTextField getTxtCustomerID() {
        return txtCustomerID;
    }

    public javax.swing.JTextField getTxtCustomerName() {
        return txtCustomerName;
    }

    public javax.swing.JTextField getTxtCustomerPhone() {
        return txtCustomerPhone;
    }

    public javax.swing.JTextField getTxtCustomerPoint() {
        return txtCustomerPoint;
    }

    
    public javax.swing.JLabel getLabelESC() {
        return labelESC;
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnAddCustomer;
    private com.k33ptoo.components.KButton btnDeleteCustomer;
    private javax.swing.JButton btnExportExcel;
    private com.k33ptoo.components.KButton btnRefresh;
    private javax.swing.JButton btnResetSort;
    private com.k33ptoo.components.KButton btnUpdate;
    private javax.swing.JComboBox<String> cbbSort;
    private javax.swing.JComboBox<String> cbbSortCustomer;
    private javax.swing.JLabel labeCreateUpdate;
    private javax.swing.JLabel labelCreateAt;
    private javax.swing.JLabel labelCustmerPhone;
    private javax.swing.JLabel labelCustomerEmail;
    private javax.swing.JLabel labelCustomerGender;
    private javax.swing.JLabel labelCustomerID;
    private javax.swing.JLabel labelCustomerName;
    private javax.swing.JLabel labelCustomerPoint;
    private javax.swing.JLabel labelESC;
    private javax.swing.JLabel labelSort;
    private javax.swing.JLabel lableTitle;
    private javax.swing.JPanel panelAction;
    private javax.swing.JPanel panelCreateAt;
    private javax.swing.JPanel panelCreateUpdate;
    private javax.swing.JPanel panelCustomerEmail;
    private javax.swing.JPanel panelCustomerGender;
    private javax.swing.JPanel panelCustomerID;
    private javax.swing.JPanel panelCustomerName;
    private javax.swing.JPanel panelCustomerPhone;
    private javax.swing.JPanel panelCustomerPoint;
    private javax.swing.JPanel panelEmpty;
    private javax.swing.JPanel panelExport;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelInfoDetail;
    private javax.swing.JPanel panelListCustomer;
    private javax.swing.JPanel panelSort;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tableCustomers;
    private com.pcstore.utils.TextFieldSearch textFieldSearch;
    private javax.swing.JTextField txtCreateAt;
    private javax.swing.JTextField txtCreateUpdate;
    private javax.swing.JTextField txtCustomerEmail;
    private javax.swing.JTextField txtCustomerGender;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerPhone;
    private javax.swing.JTextField txtCustomerPoint;
    // End of variables declaration//GEN-END:variables
}
