/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pcstore.view;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Panel;

import com.formdev.flatlaf.FlatLightLaf;
import com.k33ptoo.components.KButton;
import com.k33ptoo.components.KGradientPanel;

/**
 *
 * @author MSII
 */
public class DashboardView extends javax.swing.JFrame {

    private static DashboardView instance;

    public static DashboardView getInstance() {
        if (instance == null) {
            instance = new DashboardView();
        }
        return instance;
    }

    private Home homPanel;
    private Sell sellPanel;
    private Product productPanel;
    private Employee employeePanel;
    private WareHouse wareHousePanel;
    private Invoice invoicePanel;
    private Customer customerPanel;
    // private Service servicePanel;
    // private Report reportPanel;

    /**
     * Creates new form Menu
     */
    public DashboardView() {
        initComponents();

        homPanel = new Home();
        sellPanel = new Sell();
        productPanel = new Product();
        employeePanel = new Employee();
        invoicePanel = new Invoice();
        wareHousePanel = new WareHouse();
        customerPanel = new Customer();
        // servicePanel = new Service();
        // reportPanel = new Report();
        
        selectMenu(kPanelHome, lbMenuHome, activePanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMenu = new com.k33ptoo.components.KGradientPanel();
        lbMenu = new javax.swing.JLabel();
        kPanelHome = new com.k33ptoo.components.KGradientPanel();
        lbMenuHome = new javax.swing.JLabel();
        kPanelSell = new com.k33ptoo.components.KGradientPanel();
        lbSell = new javax.swing.JLabel();
        kPanelProduct = new com.k33ptoo.components.KGradientPanel();
        lbProductMenu = new javax.swing.JLabel();
        kPanelInvoice = new com.k33ptoo.components.KGradientPanel();
        lbMenuInvoice = new javax.swing.JLabel();
        kPanelWareHouse = new com.k33ptoo.components.KGradientPanel();
        lbMenuWareHouse = new javax.swing.JLabel();
        kPanelEmployee = new com.k33ptoo.components.KGradientPanel();
        lbMenuEmployee = new javax.swing.JLabel();
        kPanelService = new com.k33ptoo.components.KGradientPanel();
        lbMenuService = new javax.swing.JLabel();
        kPanelReport = new com.k33ptoo.components.KGradientPanel();
        lbMenuReport = new javax.swing.JLabel();
        kPanelCustomer = new com.k33ptoo.components.KGradientPanel();
        lbMenuCustomer = new javax.swing.JLabel();
        PanelNavigation = new com.k33ptoo.components.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton3 = new com.k33ptoo.components.KButton();
        lbNameUser = new javax.swing.JLabel();
        btnSignOut = new com.k33ptoo.components.KButton();
        kMainPanel = new com.k33ptoo.components.KGradientPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ CỬA HÀNG BÁN MÁY TÍNH HAL_STORE");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);

        PanelMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        PanelMenu.setkEndColor(new java.awt.Color(102, 153, 255));
        PanelMenu.setkGradientFocus(40);
        PanelMenu.setkStartColor(new java.awt.Color(153, 255, 153));
        PanelMenu.setMinimumSize(new java.awt.Dimension(100, 713));
        PanelMenu.setPreferredSize(new java.awt.Dimension(220, 680));
        PanelMenu.setLayout(new java.awt.GridLayout(11, 1, 0, 25));

        lbMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/icons8_menu_48px_1.png"))); // NOI18N
        lbMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelMenu.add(lbMenu);

        kPanelHome.setkBorderRadius(30);
        kPanelHome.setkEndColor(new java.awt.Color(255, 255, 255));
        kPanelHome.setkFillBackground(false);
        kPanelHome.setkStartColor(new java.awt.Color(255, 255, 255));
        kPanelHome.setOpaque(false);
        kPanelHome.setPreferredSize(new java.awt.Dimension(200, 10));
        kPanelHome.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        lbMenuHome.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbMenuHome.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/home_24px.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/pcstore/resources/vi_VN"); // NOI18N
        lbMenuHome.setText(bundle.getString("txtMenuHome")); // NOI18N
        lbMenuHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMenuHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMenuHomeMouseExited(evt);
            }
        });
        kPanelHome.add(lbMenuHome);

        PanelMenu.add(kPanelHome);

        kPanelSell.setkBorderRadius(30);
        kPanelSell.setkEndColor(new java.awt.Color(255, 255, 255));
        kPanelSell.setkFillBackground(false);
        kPanelSell.setkStartColor(new java.awt.Color(255, 255, 255));
        kPanelSell.setOpaque(false);
        kPanelSell.setPreferredSize(new java.awt.Dimension(200, 10));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8);
        flowLayout1.setAlignOnBaseline(true);
        kPanelSell.setLayout(flowLayout1);

        lbSell.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbSell.setForeground(new java.awt.Color(255, 255, 255));
        lbSell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/shopping_cart_24px.png"))); // NOI18N
        lbSell.setText(bundle.getString("txtMenuSell")); // NOI18N
        lbSell.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbSell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSellMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbSellMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbSellMouseExited(evt);
            }
        });
        kPanelSell.add(lbSell);

        PanelMenu.add(kPanelSell);

        kPanelProduct.setkBorderRadius(30);
        kPanelProduct.setkEndColor(new java.awt.Color(255, 255, 255));
        kPanelProduct.setkFillBackground(false);
        kPanelProduct.setkStartColor(new java.awt.Color(255, 255, 255));
        kPanelProduct.setOpaque(false);
        kPanelProduct.setPreferredSize(new java.awt.Dimension(200, 10));
        kPanelProduct.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        lbProductMenu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbProductMenu.setForeground(new java.awt.Color(255, 255, 255));
        lbProductMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/categorize_24px.png"))); // NOI18N
        lbProductMenu.setText(bundle.getString("txtMenuProduct")); // NOI18N
        lbProductMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbProductMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbProductMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbProductMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbProductMenuMouseExited(evt);
            }
        });
        kPanelProduct.add(lbProductMenu);

        PanelMenu.add(kPanelProduct);

        kPanelInvoice.setkBorderRadius(30);
        kPanelInvoice.setkEndColor(new java.awt.Color(255, 255, 255));
        kPanelInvoice.setkFillBackground(false);
        kPanelInvoice.setkStartColor(new java.awt.Color(255, 255, 255));
        kPanelInvoice.setOpaque(false);
        kPanelInvoice.setPreferredSize(new java.awt.Dimension(200, 10));
        kPanelInvoice.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        lbMenuInvoice.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbMenuInvoice.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/google_forms_24px.png"))); // NOI18N
        lbMenuInvoice.setText(bundle.getString("txtMenuInvoice")); // NOI18N
        lbMenuInvoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenuInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuInvoiceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMenuInvoiceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMenuInvoiceMouseExited(evt);
            }
        });
        kPanelInvoice.add(lbMenuInvoice);

        PanelMenu.add(kPanelInvoice);

        kPanelWareHouse.setkBorderRadius(30);
        kPanelWareHouse.setkEndColor(new java.awt.Color(255, 255, 255));
        kPanelWareHouse.setkFillBackground(false);
        kPanelWareHouse.setkStartColor(new java.awt.Color(255, 255, 255));
        kPanelWareHouse.setOpaque(false);
        kPanelWareHouse.setPreferredSize(new java.awt.Dimension(200, 10));
        kPanelWareHouse.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        lbMenuWareHouse.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbMenuWareHouse.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuWareHouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/grid_24px.png"))); // NOI18N
        lbMenuWareHouse.setText(bundle.getString("txtMenuWareHouse")); // NOI18N
        lbMenuWareHouse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenuWareHouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuWareHouseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMenuWareHouseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMenuWareHouseMouseExited(evt);
            }
        });
        kPanelWareHouse.add(lbMenuWareHouse);

        PanelMenu.add(kPanelWareHouse);

        kPanelEmployee.setkBorderRadius(30);
        kPanelEmployee.setkEndColor(new java.awt.Color(255, 255, 255));
        kPanelEmployee.setkFillBackground(false);
        kPanelEmployee.setkStartColor(new java.awt.Color(255, 255, 255));
        kPanelEmployee.setOpaque(false);
        kPanelEmployee.setPreferredSize(new java.awt.Dimension(200, 10));
        kPanelEmployee.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        lbMenuEmployee.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbMenuEmployee.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/add_user_group_woman_man_24px.png"))); // NOI18N
        lbMenuEmployee.setText(bundle.getString("txtMenuIEmployee")); // NOI18N
        lbMenuEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenuEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuEmployeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMenuEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMenuEmployeeMouseExited(evt);
            }
        });
        kPanelEmployee.add(lbMenuEmployee);

        PanelMenu.add(kPanelEmployee);

        kPanelService.setkBorderRadius(30);
        kPanelService.setkEndColor(new java.awt.Color(255, 255, 255));
        kPanelService.setkFillBackground(false);
        kPanelService.setkStartColor(new java.awt.Color(255, 255, 255));
        kPanelService.setOpaque(false);
        kPanelService.setPreferredSize(new java.awt.Dimension(200, 10));
        kPanelService.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 8));

        lbMenuService.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbMenuService.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/add_user_group_woman_man_24px.png"))); // NOI18N
        lbMenuService.setText(bundle.getString("txtMenuIService")); // NOI18N
        lbMenuService.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenuService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMenuServiceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMenuServiceMouseExited(evt);
            }
        });
        kPanelService.add(lbMenuService);

        PanelMenu.add(kPanelService);

        kPanelReport.setkBorderRadius(30);
        kPanelReport.setkEndColor(new java.awt.Color(255, 255, 255));
        kPanelReport.setkFillBackground(false);
        kPanelReport.setkStartColor(new java.awt.Color(255, 255, 255));
        kPanelReport.setOpaque(false);
        kPanelReport.setPreferredSize(new java.awt.Dimension(200, 10));
        kPanelReport.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 8));

        lbMenuReport.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbMenuReport.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/account_24px.png"))); // NOI18N
        lbMenuReport.setText(bundle.getString("txtMenuIReport")); // NOI18N
        lbMenuReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenuReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMenuReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMenuReportMouseExited(evt);
            }
        });
        kPanelReport.add(lbMenuReport);

        PanelMenu.add(kPanelReport);

        kPanelCustomer.setkBorderRadius(30);
        kPanelCustomer.setkEndColor(new java.awt.Color(255, 255, 255));
        kPanelCustomer.setkFillBackground(false);
        kPanelCustomer.setkStartColor(new java.awt.Color(255, 255, 255));
        kPanelCustomer.setOpaque(false);
        kPanelCustomer.setPreferredSize(new java.awt.Dimension(200, 10));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 8);
        flowLayout2.setAlignOnBaseline(true);
        kPanelCustomer.setLayout(flowLayout2);

        lbMenuCustomer.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbMenuCustomer.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/add_user_group_woman_man_24px.png"))); // NOI18N
        lbMenuCustomer.setText(bundle.getString("lbMenuCustomer")); // NOI18N
        lbMenuCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenuCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMenuCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMenuCustomerMouseExited(evt);
            }
        });
        kPanelCustomer.add(lbMenuCustomer);

        PanelMenu.add(kPanelCustomer);

        getContentPane().add(PanelMenu, java.awt.BorderLayout.LINE_START);

        PanelNavigation.setkEndColor(new java.awt.Color(102, 153, 255));
        PanelNavigation.setkStartColor(new java.awt.Color(153, 255, 153));
        PanelNavigation.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 30, 5));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 45));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        kButton2.setText("VI");
        kButton2.setkBorderRadius(30);
        kButton2.setkEndColor(new java.awt.Color(204, 204, 204));
        kButton2.setkStartColor(new java.awt.Color(153, 153, 153));
        kButton2.setPreferredSize(new java.awt.Dimension(100, 35));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton2);

        kButton3.setText("EN");
        kButton3.setkBorderRadius(30);
        kButton3.setkEndColor(new java.awt.Color(204, 204, 204));
        kButton3.setkStartColor(new java.awt.Color(153, 153, 153));
        kButton3.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel1.add(kButton3);

        PanelNavigation.add(jPanel1);

        lbNameUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNameUser.setForeground(new java.awt.Color(255, 255, 255));
        lbNameUser.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbNameUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/circle-user.png"))); // NOI18N
        lbNameUser.setText(bundle.getString("titleLogo")); // NOI18N
        PanelNavigation.add(lbNameUser);

        btnSignOut.setText(bundle.getString("btnSignOut")); // NOI18N
        btnSignOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSignOut.setkBorderRadius(35);
        btnSignOut.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnSignOut.setPreferredSize(new java.awt.Dimension(155, 35));
        PanelNavigation.add(btnSignOut);

        getContentPane().add(PanelNavigation, java.awt.BorderLayout.PAGE_START);

        kMainPanel.setkBorderRadius(12);
        kMainPanel.setkFillBackground(false);
        kMainPanel.setOpaque(false);
        kMainPanel.setPreferredSize(new java.awt.Dimension(1153, 0));
        kMainPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(kMainPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Start Hover=====================================================
    private void hoverPanel(KGradientPanel panel, JLabel label) {
        panel.kFillBackground = true;
        label.setForeground(new java.awt.Color(0,0,0));
        panel.repaint();
    }

    private void exitHoverPanel(KGradientPanel panel, JLabel label) {
        panel.kFillBackground = false;
        label.setForeground(new java.awt.Color(255,255,255));
        panel.repaint();
    }

    private void lbMenuHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuHomeMouseEntered
         //đổi màu nền
        hoverPanel(kPanelHome, lbMenuHome);
        
        
    }//GEN-LAST:event_lbMenuHomeMouseEntered

    private void lbMenuHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuHomeMouseExited
         //đổi màu nền
        if(activePanel != kPanelHome)
            exitHoverPanel(kPanelHome, lbMenuHome);
    }//GEN-LAST:event_lbMenuHomeMouseExited

    private void lbSellMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSellMouseEntered
        
        hoverPanel(kPanelSell, lbSell);

    }//GEN-LAST:event_lbSellMouseEntered

    private void lbSellMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSellMouseExited
        
        if(activePanel != kPanelSell)
            exitHoverPanel(kPanelSell, lbSell);
    }//GEN-LAST:event_lbSellMouseExited

    private void lbProductMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbProductMenuMouseEntered
        
        
        hoverPanel(kPanelProduct, lbProductMenu);
    }//GEN-LAST:event_lbProductMenuMouseEntered

    private void lbProductMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbProductMenuMouseExited
        
        if(activePanel != kPanelProduct)
        exitHoverPanel(kPanelProduct, lbProductMenu);
    }//GEN-LAST:event_lbProductMenuMouseExited

    private void lbMenuInvoiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuInvoiceMouseEntered
        
        hoverPanel(kPanelInvoice, lbMenuInvoice);
    }//GEN-LAST:event_lbMenuInvoiceMouseEntered

    private void lbMenuInvoiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuInvoiceMouseExited
        
        if(activePanel != kPanelInvoice)
            exitHoverPanel(kPanelInvoice, lbMenuInvoice);
    }//GEN-LAST:event_lbMenuInvoiceMouseExited

    private void lbMenuWareHouseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuWareHouseMouseEntered
        
        hoverPanel(kPanelWareHouse, lbMenuWareHouse);
    }//GEN-LAST:event_lbMenuWareHouseMouseEntered

    private void lbMenuWareHouseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuWareHouseMouseExited
        
        if(activePanel != kPanelWareHouse)
            exitHoverPanel(kPanelWareHouse, lbMenuWareHouse);
    }//GEN-LAST:event_lbMenuWareHouseMouseExited

    private void lbMenuServiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuServiceMouseEntered
        

        hoverPanel(kPanelService, lbMenuService);
    }//GEN-LAST:event_lbMenuServiceMouseEntered

    private void lbMenuServiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuServiceMouseExited
        
        if(activePanel != kPanelService)
            exitHoverPanel(kPanelService, lbMenuService);
    }//GEN-LAST:event_lbMenuServiceMouseExited

    private void lbMenuEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuEmployeeMouseEntered
        
        hoverPanel(kPanelEmployee, lbMenuEmployee);
    }//GEN-LAST:event_lbMenuEmployeeMouseEntered

    private void lbMenuEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuEmployeeMouseExited
        
        if(activePanel != kPanelEmployee)
            exitHoverPanel(kPanelEmployee, lbMenuEmployee);
    }//GEN-LAST:event_lbMenuEmployeeMouseExited

    private void lbMenuReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuReportMouseEntered
        
        hoverPanel(kPanelReport, lbMenuReport);
    }//GEN-LAST:event_lbMenuReportMouseEntered

    private void lbMenuReportMouseExited(java.awt.event.MouseEvent evt) {                                         
        
        if(activePanel != kPanelReport) 
            exitHoverPanel(kPanelReport, lbMenuReport);
    }                                                                                                        
    // Event mở từng tab====================================================================

    private void lbMenuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuHomeMouseClicked
            
        selectMenu(kPanelHome, lbMenuHome, homPanel);
    }//GEN-LAST:event_lbMenuHomeMouseClicked

    private void lbSellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSellMouseClicked
        
        selectMenu(kPanelSell, lbSell, sellPanel);
    }//GEN-LAST:event_lbSellMouseClicked

    private void lbProductMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbProductMenuMouseClicked
        
        selectMenu(kPanelProduct, lbProductMenu, productPanel);
    }//GEN-LAST:event_lbProductMenuMouseClicked

    private void lbMenuEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuEmployeeMouseClicked
        selectMenu(kPanelEmployee, lbMenuEmployee, employeePanel);
    }//GEN-LAST:event_lbMenuEmployeeMouseClicked

    private void lbMenuWareHouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuWareHouseMouseClicked
        selectMenu(kPanelWareHouse, lbMenuWareHouse, wareHousePanel);        
    }//GEN-LAST:event_lbMenuWareHouseMouseClicked

    private void lbMenuInvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuInvoiceMouseClicked
        selectMenu(kPanelInvoice, lbMenuInvoice, invoicePanel);
    }//GEN-LAST:event_lbMenuInvoiceMouseClicked

    private void lbMenuCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuCustomerMouseClicked
        selectMenu(kPanelCustomer, lbMenuCustomer, customerPanel);
    }//GEN-LAST:event_lbMenuCustomerMouseClicked

    private void lbMenuCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuCustomerMouseEntered
        hoverPanel(kPanelCustomer, lbMenuCustomer);
    }//GEN-LAST:event_lbMenuCustomerMouseEntered

    private void lbMenuCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuCustomerMouseExited
        if(activePanel != kPanelCustomer)
            exitHoverPanel(kPanelCustomer, lbMenuCustomer);
    }//GEN-LAST:event_lbMenuCustomerMouseExited

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton2ActionPerformed
    

    /**
     * Xử lý khi một menu được chọn
     * @param panel Panel menu được chọn
     * @param label Label của menu
     * @param panelContent Panel nội dung tương ứng cần hiển thị
     */
    private void selectMenu(KGradientPanel panel, JLabel label, Component component) {
        // Reset menu trước đó nếu có
        if (activePanel != null) {
            exitHoverPanel(activePanel, activeLabel);
        }
        
        // Thiết lập menu mới
        activePanel = panel;
        activeLabel = label;
        hoverPanel(panel, label);
        
        // Hiển thị nội dung tương ứng
        showComponent(component);
    }

    /**
     * Hiển thị panel nội dung trong kMainPanel
     * @param panel Panel cần hiển thị
     */
    private void showComponent(Component component) {
        // Xóa tất cả các panel đang hiển thị
        kMainPanel.removeAll();
        
        // Thiết lập layout cho kMainPanel là BorderLayout
        kMainPanel.setLayout(new BorderLayout());
        
        // Thêm panel mới
        // kMainPanel.add(panel, BorderLayout.CENTER);
        // Cập nhật hiển thị
        // Thêm component vào kMainPanel
        if (component instanceof JPanel) {
            kMainPanel.add((JPanel)component, BorderLayout.CENTER);
        } else {
            // Thêm homPanel mặc định nếu component không phải JPanel
            kMainPanel.add(homPanel, BorderLayout.CENTER);
        }

        kMainPanel.repaint();
        kMainPanel.revalidate();
    }

    

    public KGradientPanel getkMainPanel() {
        return kMainPanel;
    }

    public KGradientPanel getkPanelCustomer() {
        return kPanelCustomer;
    }

    public KGradientPanel getkPanelEmployee() {
        return kPanelEmployee;
    }

    public KGradientPanel getkPanelHome() {
        return kPanelHome;
    }

    public KGradientPanel getkPanelInvoice() {
        return kPanelInvoice;
    }

    public KGradientPanel getkPanelProduct() {
        return kPanelProduct;
    }

    public KGradientPanel getkPanelReport() {
        return kPanelReport;
    }

    public KGradientPanel getkPanelSell() {
        return kPanelSell;
    }

    public KGradientPanel getkPanelService() {
        return kPanelService;
    }

    public KGradientPanel getkPanelWareHouse() {
        return kPanelWareHouse;
    }

    public KButton getBtnSignOut() {
        return btnSignOut;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try{
            UIManager.setLookAndFeel(new FlatLightLaf());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DashboardView dashBoard = DashboardView.getInstance();
                dashBoard.setVisible(true);
            }
        });
    }

    // Thêm biến để theo dõi panel đang được chọn
    private KGradientPanel activePanel = null;
    private JLabel activeLabel = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KGradientPanel PanelMenu;
    private com.k33ptoo.components.KGradientPanel PanelNavigation;
    private com.k33ptoo.components.KButton btnSignOut;
    private javax.swing.JPanel jPanel1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KGradientPanel kMainPanel;
    private com.k33ptoo.components.KGradientPanel kPanelCustomer;
    private com.k33ptoo.components.KGradientPanel kPanelEmployee;
    private com.k33ptoo.components.KGradientPanel kPanelHome;
    private com.k33ptoo.components.KGradientPanel kPanelInvoice;
    private com.k33ptoo.components.KGradientPanel kPanelProduct;
    private com.k33ptoo.components.KGradientPanel kPanelReport;
    private com.k33ptoo.components.KGradientPanel kPanelSell;
    private com.k33ptoo.components.KGradientPanel kPanelService;
    private com.k33ptoo.components.KGradientPanel kPanelWareHouse;
    private javax.swing.JLabel lbMenu;
    private javax.swing.JLabel lbMenuCustomer;
    private javax.swing.JLabel lbMenuEmployee;
    private javax.swing.JLabel lbMenuHome;
    private javax.swing.JLabel lbMenuInvoice;
    private javax.swing.JLabel lbMenuReport;
    private javax.swing.JLabel lbMenuService;
    private javax.swing.JLabel lbMenuWareHouse;
    private javax.swing.JLabel lbNameUser;
    private javax.swing.JLabel lbProductMenu;
    private javax.swing.JLabel lbSell;
    // End of variables declaration//GEN-END:variables
}
