/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pcstore.view;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Panel;
import javax.swing.UIManager;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Panel;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.k33ptoo.components.KGradientPanel;
/**
 *
 * @author MSII
 */
public class Dashboard extends javax.swing.JFrame {

    private static Dashboard instance;

    public static Dashboard getInstance() {
        if (instance == null) {
            instance = new Dashboard();
        }
        return instance;
    }

    private Home homPanel;
    private Sell sellPanel;
    private Product productPanel;
    private Employee employeePanel;
    private WareHouse wareHousePanel;
    private Invoice invoicePanel;
    private Customer customerPanel;
    private MainWarrantyService servicePanel;
    private RevenueDaily reportPanel;

    /**
     * Creates new form Menu
     */
    public Dashboard() {
        initComponents();

        homPanel = new Home();
        sellPanel = new Sell();
        productPanel = new Product();
        employeePanel = new Employee();
        invoicePanel = new Invoice();
        wareHousePanel = new WareHouse();
        customerPanel = new Customer();
        servicePanel = new MainWarrantyService();
        reportPanel = new RevenueDaily();
        
        selectMenu(kPanelHome, lbMenuHome, activePanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        lbMenu = new javax.swing.JLabel();
        lbMenu = new javax.swing.JLabel();
        kPanelHome = new com.k33ptoo.components.KGradientPanel();
        lbMenuHome = new javax.swing.JLabel();
        kPanelSell = new com.k33ptoo.components.KGradientPanel();
        lbSell = new javax.swing.JLabel();
        kPanelProduct = new com.k33ptoo.components.KGradientPanel();
        lbProductMenu = new javax.swing.JLabel();
        kPanelInvoice = new com.k33ptoo.components.KGradientPanel();
        lbMenuInvoice = new javax.swing.JLabel();
        kPanelWareHouse = new com.k33ptoo.components.KGradientPanel();
        lbMenuWareHouse = new javax.swing.JLabel();
        kPanelWareHouse = new com.k33ptoo.components.KGradientPanel();
        lbMenuWareHouse = new javax.swing.JLabel();
        kPanelEmployee = new com.k33ptoo.components.KGradientPanel();
        lbMenuEmployee = new javax.swing.JLabel();
        kPanelService = new com.k33ptoo.components.KGradientPanel();
        lbMenuService = new javax.swing.JLabel();
        kPanelReport = new com.k33ptoo.components.KGradientPanel();
        lbMenuReport = new javax.swing.JLabel();
        kButton1 = new com.k33ptoo.components.KButton();
        kPanelCustomer = new com.k33ptoo.components.KGradientPanel();
        lbMenuCustomer = new javax.swing.JLabel();
        kPanelCustomer = new com.k33ptoo.components.KGradientPanel();
        lbMenuCustomer = new javax.swing.JLabel();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        lbNameUser = new javax.swing.JLabel();
        kMainPanel = new com.k33ptoo.components.KGradientPanel();
        kMainPanel = new com.k33ptoo.components.KGradientPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ CỬA HÀNG BÁN MÁY TÍNH HAL_STORE");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);

        kGradientPanel1.setkEndColor(new java.awt.Color(102, 153, 255));
        kGradientPanel1.setkGradientFocus(40);
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 255, 153));

        lbMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/icons8_menu_48px_1.png"))); // NOI18N
        lbMenu.setText("jLabel1");
        lbMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/icons8_menu_48px_1.png"))); // NOI18N
        lbMenu.setText("jLabel1");
        lbMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        kPanelHome.setkBorderRadius(30);
        kPanelHome.setkEndColor(new java.awt.Color(255, 255, 255));
        kPanelHome.setkFillBackground(false);
        kPanelHome.setkStartColor(new java.awt.Color(255, 255, 255));
        kPanelHome.setOpaque(false);

        lbMenuHome.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbMenuHome.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/home_24px.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/pcstore/resources/vi_VN"); // NOI18N
        lbMenuHome.setText(bundle.getString("txtMenuHome")); // NOI18N
        lbMenuHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuHomeMouseClicked(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMenuHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMenuHomeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout kPanelHomeLayout = new javax.swing.GroupLayout(kPanelHome);
        kPanelHome.setLayout(kPanelHomeLayout);
        kPanelHomeLayout.setHorizontalGroup(
            kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelHomeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbMenuHome, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );
        kPanelHomeLayout.setVerticalGroup(
            kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMenuHome, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        kPanelSell.setkBorderRadius(30);
        kPanelSell.setkEndColor(new java.awt.Color(255, 255, 255));
        kPanelSell.setkFillBackground(false);
        kPanelSell.setkStartColor(new java.awt.Color(255, 255, 255));
        kPanelSell.setOpaque(false);

        lbSell.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbSell.setForeground(new java.awt.Color(255, 255, 255));
        lbSell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/shopping_cart_24px.png"))); // NOI18N
        lbSell.setText(bundle.getString("txtMenuSell")); // NOI18N
        lbSell.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbSell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSellMouseClicked(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSellMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbSellMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbSellMouseExited(evt);
            }
        });

        javax.swing.GroupLayout kPanelSellLayout = new javax.swing.GroupLayout(kPanelSell);
        kPanelSell.setLayout(kPanelSellLayout);
        kPanelSellLayout.setHorizontalGroup(
            kPanelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelSellLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbSell, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );
        kPanelSellLayout.setVerticalGroup(
            kPanelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelSellLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbSell, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        kPanelProduct.setkBorderRadius(30);
        kPanelProduct.setkEndColor(new java.awt.Color(255, 255, 255));
        kPanelProduct.setkFillBackground(false);
        kPanelProduct.setkStartColor(new java.awt.Color(255, 255, 255));
        kPanelProduct.setOpaque(false);

        lbProductMenu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbProductMenu.setForeground(new java.awt.Color(255, 255, 255));
        lbProductMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/categorize_24px.png"))); // NOI18N
        lbProductMenu.setText(bundle.getString("txtMenuProduct")); // NOI18N
        lbProductMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbProductMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbProductMenuMouseClicked(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbProductMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbProductMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbProductMenuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout kPanelProductLayout = new javax.swing.GroupLayout(kPanelProduct);
        kPanelProduct.setLayout(kPanelProductLayout);
        kPanelProductLayout.setHorizontalGroup(
            kPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelProductLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbProductMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );
        kPanelProductLayout.setVerticalGroup(
            kPanelProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbProductMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        kPanelInvoice.setkBorderRadius(30);
        kPanelInvoice.setkEndColor(new java.awt.Color(255, 255, 255));
        kPanelInvoice.setkFillBackground(false);
        kPanelInvoice.setkStartColor(new java.awt.Color(255, 255, 255));
        kPanelInvoice.setOpaque(false);

        lbMenuInvoice.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbMenuInvoice.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/google_forms_24px.png"))); // NOI18N
        lbMenuInvoice.setText(bundle.getString("txtMenuInvoice")); // NOI18N
        lbMenuInvoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenuInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuInvoiceMouseClicked(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuInvoiceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMenuInvoiceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMenuInvoiceMouseExited(evt);
            }
        });

        javax.swing.GroupLayout kPanelInvoiceLayout = new javax.swing.GroupLayout(kPanelInvoice);
        kPanelInvoice.setLayout(kPanelInvoiceLayout);
        kPanelInvoiceLayout.setHorizontalGroup(
            kPanelInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelInvoiceLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbMenuInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );
        kPanelInvoiceLayout.setVerticalGroup(
            kPanelInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelInvoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMenuInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        kPanelWareHouse.setkBorderRadius(30);
        kPanelWareHouse.setkEndColor(new java.awt.Color(255, 255, 255));
        kPanelWareHouse.setkFillBackground(false);
        kPanelWareHouse.setkStartColor(new java.awt.Color(255, 255, 255));
        kPanelWareHouse.setOpaque(false);
        kPanelWareHouse.setkBorderRadius(30);
        kPanelWareHouse.setkEndColor(new java.awt.Color(255, 255, 255));
        kPanelWareHouse.setkFillBackground(false);
        kPanelWareHouse.setkStartColor(new java.awt.Color(255, 255, 255));
        kPanelWareHouse.setOpaque(false);

        lbMenuWareHouse.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbMenuWareHouse.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuWareHouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/grid_24px.png"))); // NOI18N
        lbMenuWareHouse.setText(bundle.getString("txtMenuWareHouse")); // NOI18N
        lbMenuWareHouse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenuWareHouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuWareHouseMouseClicked(evt);
            }
        lbMenuWareHouse.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbMenuWareHouse.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuWareHouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/grid_24px.png"))); // NOI18N
        lbMenuWareHouse.setText(bundle.getString("txtMenuWareHouse")); // NOI18N
        lbMenuWareHouse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenuWareHouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuWareHouseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMenuWareHouseMouseEntered(evt);
                lbMenuWareHouseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMenuWareHouseMouseExited(evt);
                lbMenuWareHouseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout kPanelWareHouseLayout = new javax.swing.GroupLayout(kPanelWareHouse);
        kPanelWareHouse.setLayout(kPanelWareHouseLayout);
        kPanelWareHouseLayout.setHorizontalGroup(
            kPanelWareHouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelWareHouseLayout.createSequentialGroup()
        javax.swing.GroupLayout kPanelWareHouseLayout = new javax.swing.GroupLayout(kPanelWareHouse);
        kPanelWareHouse.setLayout(kPanelWareHouseLayout);
        kPanelWareHouseLayout.setHorizontalGroup(
            kPanelWareHouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelWareHouseLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbMenuWareHouse, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addComponent(lbMenuWareHouse, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );
        kPanelWareHouseLayout.setVerticalGroup(
            kPanelWareHouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelWareHouseLayout.createSequentialGroup()
        kPanelWareHouseLayout.setVerticalGroup(
            kPanelWareHouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelWareHouseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMenuWareHouse, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addComponent(lbMenuWareHouse, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        kPanelEmployee.setkBorderRadius(30);
        kPanelEmployee.setkEndColor(new java.awt.Color(255, 255, 255));
        kPanelEmployee.setkFillBackground(false);
        kPanelEmployee.setkStartColor(new java.awt.Color(255, 255, 255));
        kPanelEmployee.setOpaque(false);

        lbMenuEmployee.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbMenuEmployee.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/add_user_group_woman_man_24px.png"))); // NOI18N
        lbMenuEmployee.setText(bundle.getString("txtMenuIEmployee")); // NOI18N
        lbMenuEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenuEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuEmployeeMouseClicked(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuEmployeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMenuEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMenuEmployeeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout kPanelEmployeeLayout = new javax.swing.GroupLayout(kPanelEmployee);
        kPanelEmployee.setLayout(kPanelEmployeeLayout);
        kPanelEmployeeLayout.setHorizontalGroup(
            kPanelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelEmployeeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbMenuEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );
        kPanelEmployeeLayout.setVerticalGroup(
            kPanelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMenuEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        kPanelService.setkBorderRadius(30);
        kPanelService.setkEndColor(new java.awt.Color(255, 255, 255));
        kPanelService.setkFillBackground(false);
        kPanelService.setkStartColor(new java.awt.Color(255, 255, 255));
        kPanelService.setOpaque(false);

        lbMenuService.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbMenuService.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/add_user_group_woman_man_24px.png"))); // NOI18N
        lbMenuService.setText(bundle.getString("txtMenuIService")); // NOI18N
        lbMenuService.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenuService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuServiceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMenuServiceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMenuServiceMouseExited(evt);
            }
        });

        javax.swing.GroupLayout kPanelServiceLayout = new javax.swing.GroupLayout(kPanelService);
        kPanelService.setLayout(kPanelServiceLayout);
        kPanelServiceLayout.setHorizontalGroup(
            kPanelServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelServiceLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbMenuService, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );
        kPanelServiceLayout.setVerticalGroup(
            kPanelServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelServiceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMenuService, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        kPanelReport.setkBorderRadius(30);
        kPanelReport.setkEndColor(new java.awt.Color(255, 255, 255));
        kPanelReport.setkFillBackground(false);
        kPanelReport.setkStartColor(new java.awt.Color(255, 255, 255));
        kPanelReport.setOpaque(false);

        lbMenuReport.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbMenuReport.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/account_24px.png"))); // NOI18N
        lbMenuReport.setText(bundle.getString("txtMenuIReport")); // NOI18N
        lbMenuReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenuReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMenuReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMenuReportMouseExited(evt);
            }
        });

        javax.swing.GroupLayout kPanelReportLayout = new javax.swing.GroupLayout(kPanelReport);
        kPanelReport.setLayout(kPanelReportLayout);
        kPanelReportLayout.setHorizontalGroup(
            kPanelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelReportLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbMenuReport, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );
        kPanelReportLayout.setVerticalGroup(
            kPanelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMenuReport, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        kButton1.setText(bundle.getString("btnSignOut")); // NOI18N
        kButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kButton1.setkBorderRadius(35);
        kButton1.setkHoverForeGround(new java.awt.Color(255, 255, 255));

        kPanelCustomer.setkBorderRadius(30);
        kPanelCustomer.setkEndColor(new java.awt.Color(255, 255, 255));
        kPanelCustomer.setkFillBackground(false);
        kPanelCustomer.setkStartColor(new java.awt.Color(255, 255, 255));
        kPanelCustomer.setOpaque(false);

        lbMenuCustomer.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbMenuCustomer.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/add_user_group_woman_man_24px.png"))); // NOI18N
        lbMenuCustomer.setText(bundle.getString("lbMenuCustomer")); // NOI18N
        lbMenuCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenuCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMenuCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMenuCustomerMouseExited(evt);
            }
        });

        javax.swing.GroupLayout kPanelCustomerLayout = new javax.swing.GroupLayout(kPanelCustomer);
        kPanelCustomer.setLayout(kPanelCustomerLayout);
        kPanelCustomerLayout.setHorizontalGroup(
            kPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelCustomerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbMenuCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );
        kPanelCustomerLayout.setVerticalGroup(
            kPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMenuCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        kPanelCustomer.setkBorderRadius(30);
        kPanelCustomer.setkEndColor(new java.awt.Color(255, 255, 255));
        kPanelCustomer.setkFillBackground(false);
        kPanelCustomer.setkStartColor(new java.awt.Color(255, 255, 255));
        kPanelCustomer.setOpaque(false);

        lbMenuCustomer.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbMenuCustomer.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/add_user_group_woman_man_24px.png"))); // NOI18N
        lbMenuCustomer.setText(bundle.getString("lbMenuCustomer")); // NOI18N
        lbMenuCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenuCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMenuCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMenuCustomerMouseExited(evt);
            }
        });

        javax.swing.GroupLayout kPanelCustomerLayout = new javax.swing.GroupLayout(kPanelCustomer);
        kPanelCustomer.setLayout(kPanelCustomerLayout);
        kPanelCustomerLayout.setHorizontalGroup(
            kPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelCustomerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbMenuCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );
        kPanelCustomerLayout.setVerticalGroup(
            kPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMenuCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kPanelSell, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kPanelProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kPanelInvoice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kPanelHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kPanelWareHouse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kPanelEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kPanelService, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kPanelCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kPanelSell, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kPanelProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kPanelInvoice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kPanelHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kPanelWareHouse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kPanelEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kPanelService, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kPanelCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kPanelReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap()
                .addComponent(kPanelReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kGradientPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {kPanelHome, kPanelInvoice, kPanelProduct, kPanelSell});

        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(lbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(kPanelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kPanelSell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kPanelProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kPanelInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kPanelWareHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(kPanelWareHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kPanelService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kPanelEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kPanelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kPanelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kPanelReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
                .addGap(41, 41, 41))
        );

        kGradientPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {kPanelHome, kPanelInvoice, kPanelProduct, kPanelSell});

        kGradientPanel2.setkEndColor(new java.awt.Color(102, 153, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(153, 255, 153));

        lbNameUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNameUser.setForeground(new java.awt.Color(255, 255, 255));
        lbNameUser.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbNameUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/circle-user.png"))); // NOI18N
        lbNameUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/circle-user.png"))); // NOI18N
        lbNameUser.setText(bundle.getString("titleLogo")); // NOI18N

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(885, Short.MAX_VALUE)
                .addComponent(lbNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
                .addContainerGap(885, Short.MAX_VALUE)
                .addComponent(lbNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbNameUser, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addComponent(lbNameUser, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        kMainPanel.setkBorderRadius(12);
        kMainPanel.setkFillBackground(false);
        kMainPanel.setOpaque(false);
        kMainPanel.setkBorderRadius(12);
        kMainPanel.setkFillBackground(false);
        kMainPanel.setOpaque(false);

        javax.swing.GroupLayout kMainPanelLayout = new javax.swing.GroupLayout(kMainPanel);
        kMainPanel.setLayout(kMainPanelLayout);
        kMainPanelLayout.setHorizontalGroup(
            kMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        javax.swing.GroupLayout kMainPanelLayout = new javax.swing.GroupLayout(kMainPanel);
        kMainPanel.setLayout(kMainPanelLayout);
        kMainPanelLayout.setHorizontalGroup(
            kMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        kMainPanelLayout.setVerticalGroup(
            kMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        kMainPanelLayout.setVerticalGroup(
            kMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Start Hover=====================================================
    // Start Hover=====================================================
    private void hoverPanel(KGradientPanel panel, JLabel label) {
        panel.kFillBackground = true;
        label.setForeground(new java.awt.Color(0,0,0));
        panel.repaint();
    }

    private void exitHoverPanel(KGradientPanel panel, JLabel label) {
        panel.kFillBackground = false;
        label.setForeground(new java.awt.Color(255,255,255));
        panel.repaint();
    }

    private void lbMenuHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuHomeMouseEntered
         //đổi màu nền
         //đổi màu nền
        hoverPanel(kPanelHome, lbMenuHome);
        
        
    }//GEN-LAST:event_lbMenuHomeMouseEntered

    private void lbMenuHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuHomeMouseExited
         //đổi màu nền
        if(activePanel != kPanelHome)
            exitHoverPanel(kPanelHome, lbMenuHome);
         //đổi màu nền
        if(activePanel != kPanelHome)
            exitHoverPanel(kPanelHome, lbMenuHome);
    }//GEN-LAST:event_lbMenuHomeMouseExited

    private void lbSellMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSellMouseEntered
        
        
        hoverPanel(kPanelSell, lbSell);

    }//GEN-LAST:event_lbSellMouseEntered

    private void lbSellMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSellMouseExited
        
        if(activePanel != kPanelSell)
            exitHoverPanel(kPanelSell, lbSell);
        
        if(activePanel != kPanelSell)
            exitHoverPanel(kPanelSell, lbSell);
    }//GEN-LAST:event_lbSellMouseExited

    private void lbProductMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbProductMenuMouseEntered
        
        
        
        
        hoverPanel(kPanelProduct, lbProductMenu);
    }//GEN-LAST:event_lbProductMenuMouseEntered

    private void lbProductMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbProductMenuMouseExited
        
        if(activePanel != kPanelProduct)
        
        if(activePanel != kPanelProduct)
        exitHoverPanel(kPanelProduct, lbProductMenu);
    }//GEN-LAST:event_lbProductMenuMouseExited

    private void lbMenuInvoiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuInvoiceMouseEntered
        
        
        hoverPanel(kPanelInvoice, lbMenuInvoice);
    }//GEN-LAST:event_lbMenuInvoiceMouseEntered

    private void lbMenuInvoiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuInvoiceMouseExited
        
        if(activePanel != kPanelInvoice)
            exitHoverPanel(kPanelInvoice, lbMenuInvoice);
        
        if(activePanel != kPanelInvoice)
            exitHoverPanel(kPanelInvoice, lbMenuInvoice);
    }//GEN-LAST:event_lbMenuInvoiceMouseExited

    private void lbMenuWareHouseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuWareHouseMouseEntered
        
        hoverPanel(kPanelWareHouse, lbMenuWareHouse);
    }//GEN-LAST:event_lbMenuWareHouseMouseEntered
    private void lbMenuWareHouseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuWareHouseMouseEntered
        
        hoverPanel(kPanelWareHouse, lbMenuWareHouse);
    }//GEN-LAST:event_lbMenuWareHouseMouseEntered

    private void lbMenuWareHouseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuWareHouseMouseExited
        
        if(activePanel != kPanelWareHouse)
            exitHoverPanel(kPanelWareHouse, lbMenuWareHouse);
    }//GEN-LAST:event_lbMenuWareHouseMouseExited
    private void lbMenuWareHouseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuWareHouseMouseExited
        
        if(activePanel != kPanelWareHouse)
            exitHoverPanel(kPanelWareHouse, lbMenuWareHouse);
    }//GEN-LAST:event_lbMenuWareHouseMouseExited

    private void lbMenuServiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuServiceMouseEntered
        

        

        hoverPanel(kPanelService, lbMenuService);
    }//GEN-LAST:event_lbMenuServiceMouseEntered

    private void lbMenuServiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuServiceMouseExited
        
        if(activePanel != kPanelService)
            exitHoverPanel(kPanelService, lbMenuService);
        
        if(activePanel != kPanelService)
            exitHoverPanel(kPanelService, lbMenuService);
    }//GEN-LAST:event_lbMenuServiceMouseExited

    private void lbMenuEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuEmployeeMouseEntered
        
        
        hoverPanel(kPanelEmployee, lbMenuEmployee);
    }//GEN-LAST:event_lbMenuEmployeeMouseEntered

    private void lbMenuEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuEmployeeMouseExited
        
        if(activePanel != kPanelEmployee)
            exitHoverPanel(kPanelEmployee, lbMenuEmployee);
        
        if(activePanel != kPanelEmployee)
            exitHoverPanel(kPanelEmployee, lbMenuEmployee);
    }//GEN-LAST:event_lbMenuEmployeeMouseExited

    private void lbMenuReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuReportMouseEntered
        
        
        hoverPanel(kPanelReport, lbMenuReport);
    }//GEN-LAST:event_lbMenuReportMouseEntered

    private void lbMenuReportMouseExited(java.awt.event.MouseEvent evt) {                                         
        
        if(activePanel != kPanelReport) 
            exitHoverPanel(kPanelReport, lbMenuReport);
    }                                                                                                        
    // Event mở từng tab====================================================================

    private void lbMenuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuHomeMouseClicked
            
        selectMenu(kPanelHome, lbMenuHome, homPanel);
    }//GEN-LAST:event_lbMenuHomeMouseClicked

    private void lbSellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSellMouseClicked
        
        selectMenu(kPanelSell, lbSell, sellPanel);
    }//GEN-LAST:event_lbSellMouseClicked

    private void lbProductMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbProductMenuMouseClicked
        
        selectMenu(kPanelProduct, lbProductMenu, productPanel);
    }//GEN-LAST:event_lbProductMenuMouseClicked

    private void lbMenuEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuEmployeeMouseClicked
        selectMenu(kPanelEmployee, lbMenuEmployee, employeePanel);
    }//GEN-LAST:event_lbMenuEmployeeMouseClicked

    private void lbMenuWareHouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuWareHouseMouseClicked
        selectMenu(kPanelWareHouse, lbMenuWareHouse, wareHousePanel);        
    }//GEN-LAST:event_lbMenuWareHouseMouseClicked

    private void lbMenuInvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuInvoiceMouseClicked
        selectMenu(kPanelInvoice, lbMenuInvoice, invoicePanel);
    }//GEN-LAST:event_lbMenuInvoiceMouseClicked

    private void lbMenuCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuCustomerMouseClicked
        selectMenu(kPanelCustomer, lbMenuCustomer, customerPanel);
    }//GEN-LAST:event_lbMenuCustomerMouseClicked

    private void lbMenuCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuCustomerMouseEntered
        hoverPanel(kPanelCustomer, lbMenuCustomer);
    }//GEN-LAST:event_lbMenuCustomerMouseEntered

    private void lbMenuCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuCustomerMouseExited
        if(activePanel != kPanelCustomer)
            exitHoverPanel(kPanelCustomer, lbMenuCustomer);
    }//GEN-LAST:event_lbMenuCustomerMouseExited
    
    private void lbMenuServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuServiceMouseClicked
        selectMenu(kPanelService, lbMenuService, servicePanel);
    }//GEN-LAST:event_lbMenuServiceMouseClicked

    private void lbMenuReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuReportMouseClicked
       selectMenu(kPanelReport, lbMenuReport, reportPanel);
    }//GEN-LAST:event_lbMenuReportMouseClicked
    
    

    /**
     * Xử lý khi một menu được chọn
     * @param panel Panel menu được chọn
     * @param label Label của menu
     * @param panelContent Panel nội dung tương ứng cần hiển thị
     */
    private void selectMenu(KGradientPanel panel, JLabel label, Component component) {
        // Reset menu trước đó nếu có
        if (activePanel != null) {
            exitHoverPanel(activePanel, activeLabel);
        }
        
        // Thiết lập menu mới
        activePanel = panel;
        activeLabel = label;
        hoverPanel(panel, label);
        
        // Hiển thị nội dung tương ứng
        showComponent(component);
    }

    /**
     * Hiển thị panel nội dung trong kMainPanel
     * @param panel Panel cần hiển thị
     */
    private void showComponent(Component component) {
        // Xóa tất cả các panel đang hiển thị
        kMainPanel.removeAll();
        
        // Thiết lập layout cho kMainPanel là BorderLayout
        kMainPanel.setLayout(new BorderLayout());
        
        // Thêm panel mới
        // kMainPanel.add(panel, BorderLayout.CENTER);
        // Cập nhật hiển thị
        // Thêm component vào kMainPanel
        if (component instanceof JPanel) {
            kMainPanel.add((JPanel)component, BorderLayout.CENTER);
        } else {
            // Thêm homPanel mặc định nếu component không phải JPanel
            kMainPanel.add(homPanel, BorderLayout.CENTER);
        }

        kMainPanel.repaint();
        kMainPanel.revalidate();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try{
            UIManager.setLookAndFeel(new FlatLightLaf());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        try{
            UIManager.setLookAndFeel(new FlatLightLaf());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dashboard dashBoard = Dashboard.getInstance();
                dashBoard.setVisible(true);
                Dashboard dashBoard = Dashboard.getInstance();
                dashBoard.setVisible(true);
            }
        });
    }

    // Thêm biến để theo dõi panel đang được chọn
    private KGradientPanel activePanel = null;
    private JLabel activeLabel = null;

    // Thêm biến để theo dõi panel đang được chọn
    private KGradientPanel activePanel = null;
    private JLabel activeLabel = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private com.k33ptoo.components.KGradientPanel kMainPanel;
    private com.k33ptoo.components.KGradientPanel kPanelCustomer;
    private com.k33ptoo.components.KGradientPanel kMainPanel;
    private com.k33ptoo.components.KGradientPanel kPanelCustomer;
    private com.k33ptoo.components.KGradientPanel kPanelEmployee;
    private com.k33ptoo.components.KGradientPanel kPanelHome;
    private com.k33ptoo.components.KGradientPanel kPanelInvoice;
    private com.k33ptoo.components.KGradientPanel kPanelProduct;
    private com.k33ptoo.components.KGradientPanel kPanelReport;
    private com.k33ptoo.components.KGradientPanel kPanelSell;
    private com.k33ptoo.components.KGradientPanel kPanelService;
    private com.k33ptoo.components.KGradientPanel kPanelWareHouse;
    private javax.swing.JLabel lbMenu;
    private javax.swing.JLabel lbMenuCustomer;
    private com.k33ptoo.components.KGradientPanel kPanelWareHouse;
    private javax.swing.JLabel lbMenu;
    private javax.swing.JLabel lbMenuCustomer;
    private javax.swing.JLabel lbMenuEmployee;
    private javax.swing.JLabel lbMenuHome;
    private javax.swing.JLabel lbMenuInvoice;
    private javax.swing.JLabel lbMenuReport;
    private javax.swing.JLabel lbMenuService;
    private javax.swing.JLabel lbMenuWareHouse;
    private javax.swing.JLabel lbMenuWareHouse;
    private javax.swing.JLabel lbNameUser;
    private javax.swing.JLabel lbProductMenu;
    private javax.swing.JLabel lbSell;
    // End of variables declaration//GEN-END:variables
}
