/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pcstore.view;

/**
 *
 * @author MSII
 */
public class Employee extends javax.swing.JPanel {

    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserBirthday = new com.raven.datechooser.DateChooser();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        kPanelPictureEmployee = new com.k33ptoo.components.KGradientPanel();
        panelName = new javax.swing.JPanel();
        lbName = new javax.swing.JLabel();
        txtNameEmployee = new javax.swing.JTextField();
        paneIDEmployee = new javax.swing.JPanel();
        lbIDEmployee = new javax.swing.JLabel();
        txtIDEmployee = new javax.swing.JTextField();
        panelPhonenumber = new javax.swing.JPanel();
        lbPhonenumber = new javax.swing.JLabel();
        txtPhonenumberEmployee = new javax.swing.JTextField();
        panelEmail = new javax.swing.JPanel();
        lbEmail = new javax.swing.JLabel();
        txtEmailEmployee = new javax.swing.JTextField();
        panelPosition = new javax.swing.JPanel();
        txtPositionEmployee = new javax.swing.JTextField();
        lbPosition = new javax.swing.JLabel();
        panelBirthdayEmployee = new javax.swing.JPanel();
        lbBirthdayEmployee = new javax.swing.JLabel();
        txtBirthdayEmployee = new javax.swing.JTextField();
        btnChooseBirthday = new javax.swing.JButton();
        panelUsername = new javax.swing.JPanel();
        lbUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        panelPassword = new javax.swing.JPanel();
        lbPassword = new javax.swing.JLabel();
        btnResetPassword = new javax.swing.JButton();
        txtPassword = new javax.swing.JTextField();
        textFieldSearch1 = new com.pcstore.view.TextFieldSearch();
        btnAddEmployee = new com.k33ptoo.components.KButton();
        jPanel9 = new javax.swing.JPanel();
        btnUpdateEmployee = new com.k33ptoo.components.KButton();
        btnDeleteEmployee = new com.k33ptoo.components.KButton();
        jLabel1 = new javax.swing.JLabel();

        dateChooserBirthday.setTextRefernce(txtBirthdayEmployee);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/pcstore/resources/vi_VN"); // NOI18N
        jLabel3.setText(bundle.getString("txtMenuIEmployee")); // NOI18N
        jLabel3.setToolTipText(bundle.getString("txtMenuSell")); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), bundle.getString("txtBorderTitleListEmployee"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ảnh", "STT", "Mã nhân viên", "Họ và tên", "Chức vụ", "SĐT", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(3);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(5);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(15);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(30);
        }

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        kGradientPanel2.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("txtDetail"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        kGradientPanel2.setkBorderRadius(15);
        kGradientPanel2.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel2.setkFillBackground(false);
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 0, 0));

        kPanelPictureEmployee.setkFillBackground(false);

        javax.swing.GroupLayout kPanelPictureEmployeeLayout = new javax.swing.GroupLayout(kPanelPictureEmployee);
        kPanelPictureEmployee.setLayout(kPanelPictureEmployeeLayout);
        kPanelPictureEmployeeLayout.setHorizontalGroup(
            kPanelPictureEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        kPanelPictureEmployeeLayout.setVerticalGroup(
            kPanelPictureEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );

        panelName.setOpaque(false);
        panelName.setLayout(new java.awt.BorderLayout(0, 1));

        lbName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbName.setText(bundle.getString("lbName")); // NOI18N
        panelName.add(lbName, java.awt.BorderLayout.CENTER);

        txtNameEmployee.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtNameEmployee.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        panelName.add(txtNameEmployee, java.awt.BorderLayout.PAGE_END);

        paneIDEmployee.setOpaque(false);
        paneIDEmployee.setLayout(new java.awt.GridLayout(1, 0));

        lbIDEmployee.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbIDEmployee.setText(bundle.getString("lbIDEmployee")); // NOI18N
        paneIDEmployee.add(lbIDEmployee);

        txtIDEmployee.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtIDEmployee.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        txtIDEmployee.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtIDEmployee.setEnabled(false);
        paneIDEmployee.add(txtIDEmployee);

        panelPhonenumber.setOpaque(false);
        panelPhonenumber.setLayout(new java.awt.BorderLayout(0, 1));

        lbPhonenumber.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbPhonenumber.setText(bundle.getString("lbPhoneNumber")); // NOI18N
        panelPhonenumber.add(lbPhonenumber, java.awt.BorderLayout.PAGE_START);

        txtPhonenumberEmployee.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtPhonenumberEmployee.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        panelPhonenumber.add(txtPhonenumberEmployee, java.awt.BorderLayout.CENTER);

        panelEmail.setOpaque(false);
        panelEmail.setLayout(new java.awt.BorderLayout(0, 1));

        lbEmail.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbEmail.setText(bundle.getString("lbEmail")); // NOI18N
        panelEmail.add(lbEmail, java.awt.BorderLayout.CENTER);

        txtEmailEmployee.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtEmailEmployee.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        panelEmail.add(txtEmailEmployee, java.awt.BorderLayout.PAGE_END);

        panelPosition.setOpaque(false);
        panelPosition.setLayout(new java.awt.BorderLayout(0, 1));

        txtPositionEmployee.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtPositionEmployee.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        panelPosition.add(txtPositionEmployee, java.awt.BorderLayout.PAGE_END);

        lbPosition.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbPosition.setText(bundle.getString("lbPosition")); // NOI18N
        panelPosition.add(lbPosition, java.awt.BorderLayout.PAGE_START);

        panelBirthdayEmployee.setOpaque(false);
        panelBirthdayEmployee.setLayout(new java.awt.BorderLayout(2, 1));

        lbBirthdayEmployee.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbBirthdayEmployee.setText(bundle.getString("lbBirthday")); // NOI18N
        panelBirthdayEmployee.add(lbBirthdayEmployee, java.awt.BorderLayout.PAGE_START);

        txtBirthdayEmployee.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtBirthdayEmployee.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        txtBirthdayEmployee.setMinimumSize(new java.awt.Dimension(135, 23));
        txtBirthdayEmployee.setName(""); // NOI18N
        txtBirthdayEmployee.setPreferredSize(new java.awt.Dimension(135, 23));
        panelBirthdayEmployee.add(txtBirthdayEmployee, java.awt.BorderLayout.CENTER);

        btnChooseBirthday.setText("...");
        btnChooseBirthday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChooseBirthdayMouseClicked(evt);
            }
        });
        panelBirthdayEmployee.add(btnChooseBirthday, java.awt.BorderLayout.LINE_END);

        panelUsername.setOpaque(false);
        panelUsername.setLayout(new java.awt.BorderLayout(0, 1));

        lbUsername.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbUsername.setForeground(new java.awt.Color(255, 0, 51));
        lbUsername.setText(bundle.getString("lbUsername")); // NOI18N
        panelUsername.add(lbUsername, java.awt.BorderLayout.CENTER);

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        panelUsername.add(txtUsername, java.awt.BorderLayout.PAGE_END);

        panelPassword.setOpaque(false);
        panelPassword.setLayout(new java.awt.BorderLayout(0, 1));

        lbPassword.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbPassword.setForeground(new java.awt.Color(255, 0, 0));
        lbPassword.setText(bundle.getString("lbPassword")); // NOI18N
        panelPassword.add(lbPassword, java.awt.BorderLayout.CENTER);

        btnResetPassword.setText("Reset");
        panelPassword.add(btnResetPassword, java.awt.BorderLayout.LINE_END);

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        panelPassword.add(txtPassword, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kPanelPictureEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(panelUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel2Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(panelPhonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addComponent(panelPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(paneIDEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(panelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(panelName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(11, 11, 11))))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(panelBirthdayEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kPanelPictureEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(paneIDEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelBirthdayEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPhonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        textFieldSearch1.setOpaque(false);

        btnAddEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/add_user_group_woman_man_24px.png"))); // NOI18N
        btnAddEmployee.setText(bundle.getString("btnAddEmployee")); // NOI18N
        btnAddEmployee.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAddEmployee.setkBorderRadius(30);
        btnAddEmployee.setkEndColor(new java.awt.Color(153, 255, 153));
        btnAddEmployee.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        btnAddEmployee.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnAddEmployee.setkHoverStartColor(new java.awt.Color(0, 255, 0));

        jPanel9.setLayout(new java.awt.GridLayout(1, 0, 50, 0));

        btnUpdateEmployee.setText(bundle.getString("btnUpdateEmployee")); // NOI18N
        btnUpdateEmployee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdateEmployee.setkBorderRadius(30);
        btnUpdateEmployee.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnUpdateEmployee.setkHoverStartColor(new java.awt.Color(51, 255, 0));
        jPanel9.add(btnUpdateEmployee);

        btnDeleteEmployee.setText(bundle.getString("btnDeleteEmployee")); // NOI18N
        btnDeleteEmployee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDeleteEmployee.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnDeleteEmployee.setkBorderRadius(30);
        btnDeleteEmployee.setkEndColor(new java.awt.Color(255, 0, 51));
        btnDeleteEmployee.setkHoverEndColor(new java.awt.Color(255, 0, 51));
        btnDeleteEmployee.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDeleteEmployee.setkHoverStartColor(new java.awt.Color(255, 102, 102));
        btnDeleteEmployee.setkStartColor(new java.awt.Color(255, 153, 51));
        jPanel9.add(btnDeleteEmployee);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(textFieldSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(707, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(469, 469, 469)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(textFieldSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseBirthdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChooseBirthdayMouseClicked
        dateChooserBirthday.showPopup();
    }//GEN-LAST:event_btnChooseBirthdayMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnAddEmployee;
    private javax.swing.JButton btnChooseBirthday;
    private com.k33ptoo.components.KButton btnDeleteEmployee;
    private javax.swing.JButton btnResetPassword;
    private com.k33ptoo.components.KButton btnUpdateEmployee;
    private com.raven.datechooser.DateChooser dateChooserBirthday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private com.k33ptoo.components.KGradientPanel kPanelPictureEmployee;
    private javax.swing.JLabel lbBirthdayEmployee;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbIDEmployee;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbPhonenumber;
    private javax.swing.JLabel lbPosition;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JPanel paneIDEmployee;
    private javax.swing.JPanel panelBirthdayEmployee;
    private javax.swing.JPanel panelEmail;
    private javax.swing.JPanel panelName;
    private javax.swing.JPanel panelPassword;
    private javax.swing.JPanel panelPhonenumber;
    private javax.swing.JPanel panelPosition;
    private javax.swing.JPanel panelUsername;
    private com.pcstore.view.TextFieldSearch textFieldSearch1;
    private javax.swing.JTextField txtBirthdayEmployee;
    private javax.swing.JTextField txtEmailEmployee;
    private javax.swing.JTextField txtIDEmployee;
    private javax.swing.JTextField txtNameEmployee;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhonenumberEmployee;
    private javax.swing.JTextField txtPositionEmployee;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
