/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pcstore.view;

/**
 *
 * @author nloc2
 */
public class ProductForm extends javax.swing.JPanel {

    /**
     * Creates new form Product
     */
    public ProductForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        kGradientPanel3 = new com.k33ptoo.components.KGradientPanel();
        textFieldSearch1 = new com.pcstore.utils.TextFieldSearch();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cbbSortCustomer = new javax.swing.JComboBox<>();
        cbbSort = new javax.swing.JComboBox<>();
        btnResetSort = new javax.swing.JButton();
        panelBody = new javax.swing.JPanel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelDetails = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        panelDetail = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        kButton3 = new com.k33ptoo.components.KButton();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton1 = new com.k33ptoo.components.KButton();
        btnAdd3 = new com.k33ptoo.components.KButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1153, 713));
        setPreferredSize(new java.awt.Dimension(1153, 713));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/pcstore/resources/vi_VN"); // NOI18N
        jLabel2.setText(bundle.getString("txtMenuProduct")); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setMaximumSize(new java.awt.Dimension(32828, 1600000));
        jLabel2.setMinimumSize(new java.awt.Dimension(850, 34));
        jLabel2.setName(""); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(900, 30));
        add(jLabel2);

        jPanel4.setBackground(new java.awt.Color(153, 255, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Panel Cái này để tìm kiếm"));
        jPanel4.setMaximumSize(new java.awt.Dimension(328791, 1000));
        jPanel4.setMinimumSize(new java.awt.Dimension(771, 50));
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(771, 80));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        kGradientPanel3.setkFillBackground(false);
        kGradientPanel3.setMaximumSize(new java.awt.Dimension(100, 200));
        kGradientPanel3.setMinimumSize(new java.awt.Dimension(100, 41));
        kGradientPanel3.setOpaque(false);

        textFieldSearch1.setPreferredSize(new java.awt.Dimension(650, 31));
        kGradientPanel3.add(textFieldSearch1);

        jPanel4.add(kGradientPanel3);

        kGradientPanel2.setkFillBackground(false);
        kGradientPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(500, 70));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText(bundle.getString("lbSort")); // NOI18N
        jPanel5.add(jLabel12);

        cbbSortCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Không>", "Tên khách hàng", "Điểm" }));
        cbbSortCustomer.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel5.add(cbbSortCustomer);

        cbbSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Không>", "Tăng dần", "Giảm giần" }));
        cbbSort.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel5.add(cbbSort);

        btnResetSort.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/refresh.png"))); // NOI18N
        btnResetSort.setPreferredSize(new java.awt.Dimension(50, 25));
        btnResetSort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetSortMouseClicked(evt);
            }
        });
        jPanel5.add(btnResetSort);

        kGradientPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel4.add(kGradientPanel2);

        add(jPanel4);

        panelBody.setBackground(new java.awt.Color(255, 255, 255));
        panelBody.setBorder(javax.swing.BorderFactory.createEmptyBorder(21, 10, 21, 10));
        panelBody.setMinimumSize(new java.awt.Dimension(850, 612));
        panelBody.setPreferredSize(new java.awt.Dimension(850, 471));
        panelBody.setLayout(new javax.swing.BoxLayout(panelBody, javax.swing.BoxLayout.LINE_AXIS));

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 20), "Danh Sách Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        kGradientPanel1.setkBorderRadius(20);
        kGradientPanel1.setkFillBackground(false);
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(650, 570));
        kGradientPanel1.setOpaque(false);
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(650, 570));
        kGradientPanel1.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Phân Loại", "Nhà Cung Cấp", "Số Lượng", "Giá Bán", "Thông Số Kỹ Thuật", "Mô Tả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(32);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        kGradientPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelBody.add(kGradientPanel1);

        panelDetails.setBackground(new java.awt.Color(255, 255, 255));
        panelDetails.setBorder(javax.swing.BorderFactory.createTitledBorder("Cái này để hiển thị thông tin chi tiết"));
        panelDetails.setPreferredSize(new java.awt.Dimension(450, 470));
        panelDetails.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setMinimumSize(new java.awt.Dimension(230, 400));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel2.setLayout(new java.awt.GridLayout(5, 2, 40, 40));

        jPanel6.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel6.setLayout(new java.awt.GridLayout(2, 0));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText(bundle.getString("lbProductName")); // NOI18N
        jLabel3.setOpaque(true);
        jPanel6.add(jLabel3);
        jPanel6.add(jTextField2);

        jPanel2.add(jPanel6);

        jPanel3.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel3.setLayout(new java.awt.GridLayout(2, 0));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText(bundle.getString("lbProductName")); // NOI18N
        jLabel4.setOpaque(true);
        jPanel3.add(jLabel4);
        jPanel3.add(jTextField1);

        jPanel2.add(jPanel3);

        jPanel7.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel7.setLayout(new java.awt.GridLayout(2, 0));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText(bundle.getString("lbProductName")); // NOI18N
        jLabel5.setOpaque(true);
        jPanel7.add(jLabel5);
        jPanel7.add(jTextField3);

        jPanel2.add(jPanel7);

        jPanel8.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel8.setLayout(new java.awt.GridLayout(2, 0));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText(bundle.getString("lbProductName")); // NOI18N
        jLabel6.setOpaque(true);
        jPanel8.add(jLabel6);
        jPanel8.add(jTextField4);

        jPanel2.add(jPanel8);

        jPanel9.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel9.setLayout(new java.awt.GridLayout(2, 0));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText(bundle.getString("lbProductName")); // NOI18N
        jLabel7.setOpaque(true);
        jPanel9.add(jLabel7);
        jPanel9.add(jTextField5);

        jPanel2.add(jPanel9);

        jPanel10.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel10.setLayout(new java.awt.GridLayout(2, 0));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText(bundle.getString("lbProductName")); // NOI18N
        jLabel8.setOpaque(true);
        jPanel10.add(jLabel8);
        jPanel10.add(jTextField6);

        jPanel2.add(jPanel10);

        jPanel11.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel11.setLayout(new java.awt.GridLayout(2, 0));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText(bundle.getString("lbProductName")); // NOI18N
        jLabel9.setOpaque(true);
        jPanel11.add(jLabel9);
        jPanel11.add(jTextField7);

        jPanel2.add(jPanel11);

        jPanel12.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel12.setLayout(new java.awt.GridLayout(2, 0));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText(bundle.getString("lbProductName")); // NOI18N
        jLabel10.setOpaque(true);
        jPanel12.add(jLabel10);
        jPanel12.add(jTextField8);

        jPanel2.add(jPanel12);

        panelDetails.add(jPanel2, java.awt.BorderLayout.CENTER);

        panelDetail.setMinimumSize(new java.awt.Dimension(200, 80));
        panelDetail.setPreferredSize(new java.awt.Dimension(300, 100));
        panelDetail.setLayout(new javax.swing.BoxLayout(panelDetail, javax.swing.BoxLayout.Y_AXIS));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText(bundle.getString("lbProductName")); // NOI18N
        jLabel11.setOpaque(true);
        panelDetail.add(jLabel11);

        jScrollPane2.setMinimumSize(new java.awt.Dimension(16, 50));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        panelDetail.add(jScrollPane2);

        panelDetails.add(panelDetail, java.awt.BorderLayout.PAGE_END);

        panelBody.add(panelDetails);

        add(panelBody);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        kButton3.setText("Xuất Excel");
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton3);

        kButton2.setText("Xóa");
        jPanel1.add(kButton2);

        kButton1.setText("Cập nhật");
        jPanel1.add(kButton1);

        btnAdd3.setText(bundle.getString("btnAddProduct")); // NOI18N
        btnAdd3.setkBorderRadius(30);
        btnAdd3.setkEndColor(new java.awt.Color(102, 153, 255));
        btnAdd3.setkHoverEndColor(new java.awt.Color(102, 153, 255));
        btnAdd3.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnAdd3.setkHoverStartColor(new java.awt.Color(153, 255, 153));
        btnAdd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd3);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents
                                

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {
        // Xử lý sự kiện khi nhấn Enter trong jTextField6
        String inputText = jTextField6.getText();
        System.out.println("Nội dung nhập: " + inputText);
        // Thêm logic xử lý khác nếu cần
    }

    private void btnAdd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd3ActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton3ActionPerformed

    private void btnResetSortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetSortMouseClicked
        cbbSortCustomer.setSelectedIndex(0);
        cbbSort.setSelectedIndex(0);
    }//GEN-LAST:event_btnResetSortMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnAdd3;
    private javax.swing.JButton btnResetSort;
    private javax.swing.JComboBox<String> cbbSort;
    private javax.swing.JComboBox<String> cbbSortCustomer;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel3;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelDetail;
    private javax.swing.JPanel panelDetails;
    private com.pcstore.utils.TextFieldSearch textFieldSearch1;
    // End of variables declaration//GEN-END:variables
}
