/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pcstore.view;
import com.k33ptoo.components.*;
import com.pcstore.controller.PurchaseOrderController;
import com.pcstore.model.Employee;
import com.pcstore.model.Supplier;
import com.pcstore.utils.LocaleManager;
import com.pcstore.utils.TextFieldSearch;

import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.util.List;
import java.util.Properties;

import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author nloc2
 */
public class PurchaseOrderForm extends JDialog {
    private PurchaseOrderController controller;

    /**
     * Creates new form WareHouseMNM
     */
    public PurchaseOrderForm() {
        super();
        initComponents();
    }

    /**
     * Constructor with parent frame and connection
     */
    public PurchaseOrderForm(Frame parent, boolean modal, Connection connection) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Phiếu Nhập Hàng");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        // Căn giữa dữ liệu bảng
        setupTableColumns();

        // Khởi tạo controller
        controller = new PurchaseOrderController(this, connection);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        lbPurchaseOrderID = new javax.swing.JLabel();
        txtPurchaseOrderID = new javax.swing.JTextField();
        lbEmloyeesCreate = new javax.swing.JLabel();
        txtEmloyeesCreate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        SelectedProduct = new javax.swing.JTable();
        btnStockIn = new com.k33ptoo.components.KButton();
        lbTotalMoney = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JLabel();
        lbSupplier = new javax.swing.JLabel();
        cbbSupplier = new javax.swing.JComboBox<>();
        textFieldSearch1 = new com.pcstore.utils.TextFieldSearch();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 680));
        setResizable(false);

        kGradientPanel1.setkFillBackground(false);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/pcstore/resources/vi_VN"); // NOI18N
        lbPurchaseOrderID.setText(bundle.getString("lbPurchaseOrderId")); // NOI18N

        txtPurchaseOrderID.setForeground(new java.awt.Color(51, 29, 204));
        txtPurchaseOrderID.setText(bundle.getString("txtPurchaseOrderID")); // NOI18N
        txtPurchaseOrderID.setEnabled(false);

        lbEmloyeesCreate.setText(bundle.getString("lbEmloyeesCreate")); // NOI18N

        txtEmloyeesCreate.setForeground(new java.awt.Color(51, 29, 204));
        txtEmloyeesCreate.setText(bundle.getString("txtEmloyeesCreate")); // NOI18N
        txtEmloyeesCreate.setEnabled(false);

        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Máy", "Tên Máy", "Đơn Giá", "SL Tồn Kho"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ProductTable);
        if (ProductTable.getColumnModel().getColumnCount() > 0) {
            ProductTable.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("clProductID")); // NOI18N
            ProductTable.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("clProductName")); // NOI18N
            ProductTable.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("clPrice")); // NOI18N
        }

        SelectedProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Máy", "Tên Máy", "Số Lượng", "Đơn Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(SelectedProduct);
        if (SelectedProduct.getColumnModel().getColumnCount() > 0) {
            SelectedProduct.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("clProductID")); // NOI18N
            SelectedProduct.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("clProductName")); // NOI18N
            SelectedProduct.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("clQuantity")); // NOI18N
            SelectedProduct.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("clPrice")); // NOI18N
        }

        btnStockIn.setText(bundle.getString("btnCreateStockIn")); // NOI18N
        btnStockIn.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnStockIn.setkBorderRadius(40);
        btnStockIn.setkHoverEndColor(new java.awt.Color(102, 153, 255));
        btnStockIn.setkHoverForeGround(new java.awt.Color(255, 255, 255));

        lbTotalMoney.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTotalMoney.setText(bundle.getString("lbTotalMoney")); // NOI18N

        txtTotalPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTotalPrice.setForeground(new java.awt.Color(255, 51, 51));
        txtTotalPrice.setText(bundle.getString("lbTotalPrice")); // NOI18N

        lbSupplier.setText(bundle.getString("lbSupplier")); // NOI18N

        cbbSupplier.setForeground(new java.awt.Color(51, 29, 204));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbEmloyeesCreate, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                            .addComponent(lbSupplier)
                            .addGap(26, 26, 26)
                            .addComponent(cbbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                    .addComponent(lbPurchaseOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtEmloyeesCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                        .addComponent(txtPurchaseOrderID)))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(lbTotalMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnStockIn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPurchaseOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPurchaseOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEmloyeesCreate)
                            .addComponent(txtEmloyeesCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbSupplier))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(textFieldSearch1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTotalMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStockIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        getContentPane().add(kGradientPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Thiết lập các cột cho bảng và thêm sự kiện double-click
     */
    private void setupTableColumns() {
        // Căn giữa các cột
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        
        // Thiết lập căn giữa cho bảng sản phẩm
        for (int i = 0; i < ProductTable.getColumnCount(); i++) {
            ProductTable.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        // Thiết lập căn giữa cho bảng giỏ hàng
        for (int i = 0; i < SelectedProduct.getColumnCount(); i++) {
            SelectedProduct.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        javax.swing.Timer searchTimer = new javax.swing.Timer(500, e -> {
            if (controller != null) {
                controller.searchProducts();
            }
        });
        searchTimer.setRepeats(false); // Chỉ chạy một lần
        
        // Thêm sự kiện mouseClicked để xử lý double click trên bảng sản phẩm
        ProductTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {  // Double click
                    int row = ProductTable.getSelectedRow();
                    if (row != -1 && controller != null) {  // Nếu có dòng được chọn
                        // Gọi phương thức thêm sản phẩm vào giỏ hàng
                        controller.addProductToCartByRowDirect(row);
                    }
                }
            }
        });
        
        // Thêm sự kiện double click để xóa sản phẩm khỏi giỏ hàng
        SelectedProduct.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {  // Double click
                    int row = SelectedProduct.getSelectedRow();
                    if (row != -1 && controller != null) {
                        int confirm = JOptionPane.showConfirmDialog(
                                PurchaseOrderForm.this,
                                "Bạn có muốn xóa sản phẩm này khỏi phiếu nhập không?",
                                "Xác nhận", JOptionPane.YES_NO_OPTION);
                        
                        if (confirm == JOptionPane.YES_OPTION) {
                            controller.removeProductFromCart(row);
                        }
                    }
                }
            }
        });

         // Kết nối DocumentListener cho thanh tìm kiếm
    textFieldSearch1.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        @Override
        public void insertUpdate(javax.swing.event.DocumentEvent e) {
            searchTimer.restart();
        }

        @Override
        public void removeUpdate(javax.swing.event.DocumentEvent e) {
            searchTimer.restart();
        }

        @Override
        public void changedUpdate(javax.swing.event.DocumentEvent e) {
            searchTimer.restart();
        }
    });
    
    // Thêm ActionListener cho nút tìm kiếm (nếu có)
    try {
        textFieldSearch1.getBtnSearch().addActionListener(e -> {
            if (controller != null) {
                controller.searchProducts();
            }
        });
    } catch (Exception ex) {
        System.out.println("Không có phương thức getBtnSearch(): " + ex.getMessage());
    }

    }
    
    /**
     * Cập nhật ComboBox nhà cung cấp với danh sách từ database
     */
    public void updateSupplierComboBoxes(List<Supplier> suppliers) {
        // Xóa tất cả items hiện tại
        cbbSupplier.removeAllItems();
        
        // Thêm các nhà cung cấp vào combobox
        DefaultComboBoxModel<Supplier> model = new DefaultComboBoxModel<>();
        for (Supplier supplier : suppliers) {
            model.addElement(supplier);
        }
        
        // Đặt model mới cho combobox
        cbbSupplier.setModel(model);
        
        // Thiết lập renderer để hiển thị tên nhà cung cấp
        cbbSupplier.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                Component comp = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Supplier) {
                    setText(((Supplier) value).getName());
                }
                return comp;
            }
        });
        
        // Chọn item đầu tiên nếu có
        if (cbbSupplier.getItemCount() > 0) {
            cbbSupplier.setSelectedIndex(0);
        }
    }

    /**
     * Xóa sản phẩm tại vị trí chỉ định khỏi giỏ hàng
     * @param row Dòng cần xóa
     */
    public void removeProductFromCart(int row) {
        if (controller != null) {
            controller.removeProductFromCart(row);
        }
    }

    // -------------------- CÁC PHƯƠNG THỨC GETTER --------------------

    /**
     * Lấy nhà cung cấp được chọn từ ComboBox
     */
    public Supplier getSelectedSupplier() {
        if (cbbSupplier.getSelectedItem() instanceof Supplier) {
            return (Supplier) cbbSupplier.getSelectedItem();
        }
        return null;
    }
    
    /**
     * Lấy ComboBox nhà cung cấp
     */
    public JComboBox<Supplier> getSupplierComboBox() {
        return (JComboBox<Supplier>) cbbSupplier;
    }

    /**
     * Lấy TextField ID phiếu nhập
     */
    public JTextField getPurchaseOrderIdField() {
        return txtPurchaseOrderID;
    }
        /**
     * Lấy combo box nhà cung cấp - Tương thích với controller cũ
     */
    public JComboBox<Supplier> getComboBoxSupplier() {
        return (JComboBox<Supplier>) cbbSupplier;
    }
    /**
     * Lấy TextField2 - Đồng bộ với getPurchaseOrderIdField()
     */
    public JTextField getTextField2() {
        return txtPurchaseOrderID;
    }

    /**
     * Lấy TextField nhân viên
     */
    public JTextField getEmployeeField() {
        return txtEmloyeesCreate;
    }
    
    /**
     * Lấy TextField4 - Đồng bộ với getEmployeeField()
     */
    public JTextField getTextField4() {
        return txtEmloyeesCreate;
    }

    /**
     * Lấy bảng sản phẩm
     */
    public JTable getTableProducts() {
        return ProductTable;
    }
    
    /**
     * Lấy JTable1 - Đồng bộ với getTableProducts()
     */
    public JTable getJTable1() {
        return ProductTable;
    }

    /**
     * Lấy bảng sản phẩm đã chọn
     */
    public JTable getTableSelectedProducts() {
        return SelectedProduct;
    }
    
    /**
     * Lấy JTable2 - Đồng bộ với getTableSelectedProducts()
     */
    public JTable getJTable2() {
        return SelectedProduct;
    }

    /**
     * Lấy label hiển thị tổng tiền
     */
    public JLabel getLabelTotalAmount() {
        return txtTotalPrice;
    }
    
    /**
     * Lấy TxtTotalPrice - Đồng bộ với getLabelTotalAmount()
     */
    public JLabel getTxtTotalPrice() {
        return txtTotalPrice;
    }

    /**
     * Lấy nút nhập kho
     */
    public KButton getBtnStockIn() {
        return btnStockIn;
    }
    
    /**
     * Lấy nút lưu - Đồng bộ với getBtnStockIn()
     */
    public JButton getBtnSave() {
        return btnStockIn;
    }
    
    /**
     * Lấy ô tìm kiếm
     */
    public TextFieldSearch getTextFieldSearch() {
        return textFieldSearch1;
    }
    
    /**
     * Lấy label ID phiếu nhập
     */
    public JLabel getLblPurchaseOrderId() {
        return lbPurchaseOrderID;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ProductTable;
    private javax.swing.JTable SelectedProduct;
    private com.k33ptoo.components.KButton btnStockIn;
    private javax.swing.JComboBox<Supplier> cbbSupplier;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lbEmloyeesCreate;
    private javax.swing.JLabel lbPurchaseOrderID;
    private javax.swing.JLabel lbSupplier;
    private javax.swing.JLabel lbTotalMoney;
    private com.pcstore.utils.TextFieldSearch textFieldSearch1;
    private javax.swing.JTextField txtEmloyeesCreate;
    private javax.swing.JTextField txtPurchaseOrderID;
    private javax.swing.JLabel txtTotalPrice;
    // End of variables declaration//GEN-END:variables
}