/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pcstore.view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import com.k33ptoo.components.KGradientPanel;
import com.pcstore.controller.RevenueController;
import com.pcstore.utils.DatabaseConnection;

/**
 *
 * @author DUC ANH
 */
public class ReportForm extends javax.swing.JPanel {
    private KGradientPanel activePanel = null;
    private JLabel activeLabel = null;
    private RevenueDailyForm revenueDailyForm;
    private RevenueMonthlyForm revenueMonthlyForm;
    private RevenueController revenueController;
    
    /**
     * Creates new form RevenueForm - Tự khởi tạo controller
     */
    public ReportForm() {
        initComponents();
        
        // Khởi tạo các form con
        revenueDailyForm = new RevenueDailyForm();
        revenueMonthlyForm = new RevenueMonthlyForm();
        
        // Tự động khởi tạo controller và thiết lập các thành phần
        try {
            // Lấy connection từ DatabaseConnection singleton
            Connection connection = DatabaseConnection.getInstance().getConnection();
            if (connection != null) {
                // Khởi tạo controller
                revenueController = new RevenueController(connection);
                
                // Thiết lập controller cho các form con
                revenueDailyForm.setController(revenueController);
                revenueMonthlyForm.setController(revenueController);
                
                // Khởi tạo hiệu ứng hover
                initializeHoverEffects();
                
                // Chọn mặc định là form doanh thu theo ngày
                selectMenu(panelDaily, lbDaily, revenueDailyForm);
                
                System.out.println("ReportForm: Khởi tạo controller thành công");
            } else {
                System.err.println("ReportForm: Không thể kết nối database");
                JOptionPane.showMessageDialog(this, 
                    "Không thể kết nối đến cơ sở dữ liệu", 
                    "Lỗi kết nối", 
                    JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println("ReportForm: Lỗi khi khởi tạo controller - " + e.getMessage());
            JOptionPane.showMessageDialog(this,
                "Lỗi khởi tạo: " + e.getMessage(),
                "Lỗi",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNav = new javax.swing.JPanel();
        panelDaily = new com.k33ptoo.components.KGradientPanel();
        lbDaily = new javax.swing.JLabel();
        panelMonthly = new com.k33ptoo.components.KGradientPanel();
        lbMonthly = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1153, 713));
        setLayout(new java.awt.BorderLayout());

        panelNav.setBackground(new java.awt.Color(102, 153, 255));
        panelNav.setOpaque(false);
        panelNav.setPreferredSize(new java.awt.Dimension(530, 40));
        panelNav.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        panelDaily.setkBorderRadius(25);
        panelDaily.setkFillBackground(false);
        panelDaily.setOpaque(false);
        panelDaily.setPreferredSize(new java.awt.Dimension(200, 35));
        panelDaily.setLayout(new java.awt.BorderLayout());

        lbDaily.setBackground(new java.awt.Color(255, 255, 255));
        lbDaily.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDaily.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/pcstore/resources/vi_VN"); // NOI18N
        lbDaily.setText(bundle.getString("RevenueDaily")); // NOI18N
        lbDaily.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbDaily.setMaximumSize(new java.awt.Dimension(200, 20));
        lbDaily.setMinimumSize(new java.awt.Dimension(200, 20));
        lbDaily.setPreferredSize(new java.awt.Dimension(1200, 20));
        panelDaily.add(lbDaily, java.awt.BorderLayout.CENTER);

        panelNav.add(panelDaily);

        panelMonthly.setkBorderRadius(25);
        panelMonthly.setkFillBackground(false);
        panelMonthly.setOpaque(false);
        panelMonthly.setPreferredSize(new java.awt.Dimension(200, 35));
        panelMonthly.setLayout(new java.awt.BorderLayout());

        lbMonthly.setBackground(new java.awt.Color(255, 255, 255));
        lbMonthly.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMonthly.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMonthly.setText(bundle.getString("RevenueMonthly")); // NOI18N
        lbMonthly.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelMonthly.add(lbMonthly, java.awt.BorderLayout.CENTER);

        panelNav.add(panelMonthly);

        add(panelNav, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 843, Short.MAX_VALUE)
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );

        add(panelContent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
        
    // Start Hover========================================================
    private void initializeHoverEffects() {
        KGradientPanel[] panels = {panelDaily, panelMonthly};
        JLabel[] labels = {lbDaily, lbMonthly};

        for (int i = 0; i < panels.length; i++) {
            final KGradientPanel panel = panels[i];
            final JLabel label = labels[i];

            panel.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseEntered(MouseEvent evt) {
                    hoverPanel(panel, label);
                }

                @Override
                public void mouseExited(MouseEvent evt) {
                    if (activePanel != panel) {
                        exitHoverPanel(panel, label);
                    }
                }

                @Override
                public void mouseClicked(MouseEvent evt) {
                    handleMenuClick(panel, label);
                }
            });
        }
    }

    private void hoverPanel(KGradientPanel panel, JLabel label) {
        panel.kFillBackground = true;
        label.setForeground(new Color(255, 255, 255));
        panel.repaint();
    }

    private void exitHoverPanel(KGradientPanel panel, JLabel label) {
        panel.kFillBackground = false;
        label.setForeground(new Color(0, 0, 0));
        panel.repaint();
    }

    private void handleMenuClick(KGradientPanel panel, JLabel label) {
        if (panel == panelDaily) {
            selectMenu(panel, label, revenueDailyForm);
        } else if (panel == panelMonthly) {
            selectMenu(panel, label, revenueMonthlyForm);
        }
    }

    private void selectMenu(KGradientPanel panel, JLabel label, JPanel component) {
        if (activePanel != null && activeLabel != null) {
            exitHoverPanel(activePanel, activeLabel);
        }

        activePanel = panel;
        activeLabel = label;

        panel.setkFillBackground(true);
        panel.setkStartColor(new Color(102, 204, 255));
        panel.setkEndColor(new Color(0, 153, 255));
        label.setForeground(new Color(255, 255, 255));
        panel.repaint();

        showComponent(component);
    }

    private void showComponent(JPanel component) {
        panelContent.removeAll();
        panelContent.setLayout(new BorderLayout());
        panelContent.add(component, BorderLayout.CENTER);
        panelContent.repaint();
        panelContent.revalidate();
    }
    // End Hover========================================================

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbDaily;
    private javax.swing.JLabel lbMonthly;
    private javax.swing.JPanel panelContent;
    private com.k33ptoo.components.KGradientPanel panelDaily;
    private com.k33ptoo.components.KGradientPanel panelMonthly;
    private javax.swing.JPanel panelNav;
    // End of variables declaration//GEN-END:variables
}
