/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pcstore.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;

import com.k33ptoo.components.KButton;
import com.pcstore.controller.RevenueController;

/**
 *
 * @author DUC ANH
 */
public class RevenueMonthlyForm extends javax.swing.JPanel {

    private RevenueController controller;
    
    /**
     * Creates new form RevenueDaily
     */
    public RevenueMonthlyForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TotalRevenue = new javax.swing.JLabel();
        btnExportReport = new com.k33ptoo.components.KButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        TotalProfit = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1153, 610));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/pcstore/resources/vi_VN"); // NOI18N
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("RevenueDaily"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16))); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText(bundle.getString("Month")); // NOI18N

        jLabel1.setText("                                  ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText(bundle.getString("lbTotalRevenue")); // NOI18N

        TotalRevenue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TotalRevenue.setText("                     ");
        TotalRevenue.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        btnExportReport.setText(bundle.getString("btnExportreport")); // NOI18N
        btnExportReport.setkBorderRadius(30);
        btnExportReport.setkEndColor(new java.awt.Color(102, 153, 255));
        btnExportReport.setkHoverEndColor(new java.awt.Color(102, 153, 255));
        btnExportReport.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnExportReport.setkHoverStartColor(new java.awt.Color(153, 255, 153));
        btnExportReport.setkStartColor(new java.awt.Color(102, 153, 255));
        btnExportReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExportReportMouseClicked(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("pnSalesStatistics"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Đơn Giá", "Thành Tiền"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("clSTT")); // NOI18N
            jTable1.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("cl1ProductCode")); // NOI18N
            jTable1.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("clNameProduct")); // NOI18N
            jTable1.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("clQuantity")); // NOI18N
            jTable1.getColumnModel().getColumn(4).setHeaderValue(bundle.getString("clUnitPrice")); // NOI18N
            jTable1.getColumnModel().getColumn(5).setHeaderValue(bundle.getString("clMoney")); // NOI18N
        }

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText(bundle.getString("lbTotalProfit")); // NOI18N

        TotalProfit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TotalProfit.setText("                     ");
        TotalProfit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalRevenue)
                .addGap(94, 94, 94)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalProfit)
                .addContainerGap(445, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExportReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(TotalRevenue)
                    .addComponent(jLabel4)
                    .addComponent(TotalProfit))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExportReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1153, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportReportMouseClicked
        // Việc xử lý đã được chuyển sang controller
    }//GEN-LAST:event_btnExportReportMouseClicked

    /**
     * Thiết lập controller cho form
     * @param controller Controller doanh thu
     */
    public void setController(RevenueController controller) {
        this.controller = controller;
        if (controller != null) {
            controller.setRevenueMonthlyForm(this);
        }
    }
    
    /**
     * Lấy label hiển thị tháng
     * @return Label tháng
     */
    public JLabel getMonthLabel() {
        return jLabel1;
    }
    
    /**
     * Lấy nút chọn tháng
     * @return Nút tháng
     */
    public JButton getMonthButton() {
        return jButton1;
    }
    
    /**
     * Lấy label hiển thị tổng doanh thu
     * @return Label doanh thu
     */
    public JLabel getTotalRevenueLabel() {
        return TotalRevenue;
    }
    
    /**
     * Lấy label hiển thị tổng lợi nhuận
     * @return Label lợi nhuận
     */
    public JLabel getTotalProfitLabel() {
        return TotalProfit;
    }
    
    /**
     * Lấy nút xuất báo cáo
     * @return Nút xuất báo cáo
     */
    public KButton getExportButton() {
        return btnExportReport;
    }
    
    /**
     * Lấy bảng thống kê doanh thu
     * @return Bảng thống kê
     */
    public JTable getRevenueTable() {
        return jTable1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TotalProfit;
    private javax.swing.JLabel TotalRevenue;
    private com.k33ptoo.components.KButton btnExportReport;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
