/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pcstore.view;

import javax.swing.UIManager;

/**
 *
 * @author DUC ANH
 */
public class WarrantyServiceForm extends javax.swing.JPanel {

    /**
     * Creates new form Service
     */
    public WarrantyServiceForm() {
        try {
            initComponents();
            initController();
        } catch (Exception e) {
            System.err.println("Error initializing WarrantyServiceForm: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                this,
                "Lỗi khởi tạo form: " + e.getMessage(),
                "Lỗi",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    /**
     * Khởi tạo controller và tải dữ liệu ban đầu
     */
    private void initController() {
        try {
            // Khởi tạo controller với các service cần thiết
            controller = new WarrantyController(
                ServiceFactory.getWarrantyService(),
                ServiceFactory.getInvoiceService(),
                ServiceFactory.getInvoiceDetailService(),
                ServiceFactory.getProductService(),
                ServiceFactory.getCustomerService()
            );
            
            // Thiết lập form và tải dữ liệu
            controller.setServiceForm(this);
            controller.loadWarranties(); // Tải dữ liệu khi khởi tạo
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this,
                "Lỗi khởi tạo controller: " + e.getMessage(),
                "Lỗi",
                JOptionPane.ERROR_MESSAGE
            );
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnWarrantyInformationLookup = new com.k33ptoo.components.KButton();
        jTextField1 = new javax.swing.JTextField();
        btnWarrantyRegistration = new com.k33ptoo.components.KButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnDetailWarrantyCard = new com.k33ptoo.components.KButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setMaximumSize(new java.awt.Dimension(1153, 713));
        setMinimumSize(new java.awt.Dimension(1153, 713));
        setPreferredSize(new java.awt.Dimension(1153, 713));
        setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 10));

        btnWarrantyRegistration.setText(bundle.getString("btnWarrantyRegistration")); // NOI18N
        btnWarrantyRegistration.setkBorderRadius(40);
        btnWarrantyRegistration.setkEndColor(new java.awt.Color(0, 255, 51));
        btnWarrantyRegistration.setkHoverEndColor(new java.awt.Color(102, 153, 255));
        btnWarrantyRegistration.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnWarrantyRegistration.setkHoverStartColor(new java.awt.Color(153, 255, 153));
        btnWarrantyRegistration.setkStartColor(new java.awt.Color(0, 204, 255));
        btnWarrantyRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWarrantyRegistrationActionPerformed(evt);
            }
        });
        jPanel2.add(btnWarrantyRegistration);

        btnRemoveRepair.setText(bundle.getString("btnRemoveRepair")); // NOI18N
        btnRemoveRepair.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRemoveRepair.setkBorderRadius(40);
        btnRemoveRepair.setkEndColor(new java.awt.Color(255, 102, 51));
        btnRemoveRepair.setkHoverEndColor(new java.awt.Color(102, 153, 255));
        btnRemoveRepair.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnRemoveRepair.setkHoverStartColor(new java.awt.Color(153, 255, 153));
        btnRemoveRepair.setkStartColor(new java.awt.Color(255, 0, 51));
        btnRemoveRepair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoveRepairMouseClicked(evt);
            }
        });
        btnRemoveRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveRepairActionPerformed(evt);
            }
        });
        jPanel2.add(btnRemoveRepair);

        btnDetailWarrantyCard.setText(bundle.getString("btnDetailWarrantyCard")); // NOI18N
        btnDetailWarrantyCard.setkBorderRadius(40);
        btnDetailWarrantyCard.setkEndColor(new java.awt.Color(102, 153, 255));
        btnDetailWarrantyCard.setkHoverEndColor(new java.awt.Color(102, 153, 255));
        btnDetailWarrantyCard.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDetailWarrantyCard.setkHoverStartColor(new java.awt.Color(153, 255, 153));
        btnDetailWarrantyCard.setkStartColor(new java.awt.Color(102, 153, 255));
        btnDetailWarrantyCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailWarrantyCardActionPerformed(evt);
            }
        });
        jPanel2.add(btnDetailWarrantyCard);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm Kiếm"));
        jPanel3.setPreferredSize(new java.awt.Dimension(425, 65));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/pcstore/resources/vi_VN"); // NOI18N
        btnWarrantyInformationLookup.setText(bundle.getString("btnWarrantyInformationLookup")); // NOI18N
        btnWarrantyInformationLookup.setkBackGroundColor(new java.awt.Color(102, 153, 255));
        btnWarrantyInformationLookup.setkBorderRadius(30);
        btnWarrantyInformationLookup.setkEndColor(new java.awt.Color(153, 153, 153));
        btnWarrantyInformationLookup.setkHoverEndColor(new java.awt.Color(102, 153, 255));
        btnWarrantyInformationLookup.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnWarrantyInformationLookup.setkHoverStartColor(new java.awt.Color(153, 255, 153));
        btnWarrantyInformationLookup.setkStartColor(new java.awt.Color(102, 153, 255));
        btnWarrantyInformationLookup.setMargin(new java.awt.Insets(2, 14, 0, 14));
        btnWarrantyInformationLookup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWarrantyInformationLookupActionPerformed(evt);
            }
        });
        jPanel3.add(btnWarrantyInformationLookup, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 70, 32));

        jTextField1.setMargin(new java.awt.Insets(2, 6, 2, 0));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 292, 30));

        jPanel2.add(jPanel3);

        btnWarrantyRegistration.setText(bundle.getString("btnWarrantyRegistration")); // NOI18N
        btnWarrantyRegistration.setkEndColor(new java.awt.Color(102, 153, 255));
        btnWarrantyRegistration.setkHoverEndColor(new java.awt.Color(102, 153, 255));
        btnWarrantyRegistration.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnWarrantyRegistration.setkHoverStartColor(new java.awt.Color(153, 255, 153));
        btnWarrantyRegistration.setkStartColor(new java.awt.Color(102, 153, 255));
        btnWarrantyRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWarrantyRegistrationMouseClicked(evt);
            }
        });
        jPanel2.add(btnWarrantyRegistration);

        jPanel5.add(jPanel2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Bảo Hành ", "Ngày Yêu Cầu", "Mã Khách Hàng", "Tên Khách Hàng", "Số Điện Thoại", "Tên sản Phẩm ", "Mã Sản Phẩm", "Tình Trạng"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 20));

        btnDetailWarrantyCard.setText(bundle.getString("btnDetailWarrantyCard")); // NOI18N
        btnDetailWarrantyCard.setkEndColor(new java.awt.Color(102, 153, 255));
        btnDetailWarrantyCard.setkHoverEndColor(new java.awt.Color(102, 153, 255));
        btnDetailWarrantyCard.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDetailWarrantyCard.setkHoverStartColor(new java.awt.Color(153, 255, 153));
        btnDetailWarrantyCard.setkStartColor(new java.awt.Color(102, 153, 255));
        jPanel4.add(btnDetailWarrantyCard);

        jPanel5.add(jPanel4);

        add(jPanel5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnWarrantyRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWarrantyRegistrationActionPerformed
        try {
            // Kiểm tra controller
            if (controller == null) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Controller chưa được khởi tạo.",
                    "Lỗi",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Tạo dialog mới
            javax.swing.JDialog dialog = new javax.swing.JDialog();
            dialog.setTitle("Đăng ký bảo hành mới");
            dialog.setModal(true);
            dialog.setSize(980, 650);
            dialog.setLocationRelativeTo(this);
            
            // Tạo form đăng ký bảo hành và thêm vào dialog
            AddWarrantyForm addWarrantyForm = new AddWarrantyForm(controller);
            dialog.add(addWarrantyForm);
            
            // Hiển thị dialog
            dialog.setVisible(true);
            
            // Sau khi dialog đóng, cập nhật lại danh sách bảo hành
            controller.loadWarranties();
            
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                "Lỗi khi mở form đăng ký bảo hành: " + e.getMessage(),
                "Lỗi",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnWarrantyRegistrationActionPerformed

    private void btnRemoveRepairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveRepairMouseClicked
        // Gọi phương thức xử lý sự kiện action để tránh lặp code
        btnRemoveRepairActionPerformed(null);
    }//GEN-LAST:event_btnRemoveRepairMouseClicked

    private void btnRemoveRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveRepairActionPerformed
        try {
            // Kiểm tra xem có hàng nào được chọn không
            int selectedRow = jTable1.getSelectedRow();
            if (selectedRow == -1) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Vui lòng chọn một bảo hành để xóa.",
                    "Thông báo",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            // Lấy ID của bảo hành được chọn
            Object warrantyIdObj = jTable1.getValueAt(selectedRow, 0);
            if (warrantyIdObj == null || warrantyIdObj.toString().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Bảo hành không có ID hợp lệ.",
                    "Lỗi",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            Integer warrantyId = null;
            // try {
            //     warrantyId = Integer.parseInt(warrantyIdObj.toString());
            // } catch (NumberFormatException e) {
            //     javax.swing.JOptionPane.showMessageDialog(this,
            //         "ID bảo hành không hợp lệ: " + warrantyIdObj,
            //         "Lỗi",
            //         javax.swing.JOptionPane.ERROR_MESSAGE);
            //     return;
            // }

            // Kiểm tra controller
            if (controller == null) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Controller chưa được khởi tạo.",
                    "Lỗi",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Xác nhận trước khi xóa
            int choice = javax.swing.JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn muốn xóa bảo hành này không?",
                "Xác nhận xóa",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE);

            if (choice != javax.swing.JOptionPane.YES_OPTION) {
                return; // Người dùng đã hủy việc xóa
            }

            // Tiến hành xóa bảo hành
            boolean success = controller.deleteWarranty(warrantyId);

            if (success) {
                // Hiển thị thông báo thành công
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Đã xóa bảo hành thành công!",
                    "Thành công",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

                // Cập nhật lại bảng
                controller.loadWarranties();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Không thể xóa bảo hành. Vui lòng thử lại sau.",
                    "Lỗi",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                "Lỗi khi xóa bảo hành: " + e.getMessage(),
                "Lỗi",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoveRepairActionPerformed

    private void btnDetailWarrantyCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailWarrantyCardActionPerformed
        if (controller != null) {
            int selectedRow = jTable1.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(
                    this,
                    "Vui lòng chọn một bảo hành để xem chi tiết",
                    "Chưa Chọn",
                    JOptionPane.WARNING_MESSAGE
                );
                return;
            }
            
            // Lấy mã bảo hành từ dòng đã chọn
            String warrantyId = jTable1.getValueAt(selectedRow, 0).toString();
            controller.viewWarrantyDetail(warrantyId);
        }
    }//GEN-LAST:event_btnDetailWarrantyCardActionPerformed

    private void btnWarrantyInformationLookupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWarrantyInformationLookupActionPerformed
        if (controller != null) {
            String keyword = jTextField1.getText().trim();
            controller.searchWarranties(keyword);
        }
    }//GEN-LAST:event_btnWarrantyInformationLookupActionPerformed
   
    

    /**
     * Cập nhật dữ liệu bảng bảo hành từ danh sách
     * @param warranties Danh sách bảo hành để hiển thị
     */
    public void updateWarrantyTable(List<Warranty> warranties) {
        System.out.println("Updating warranty table with " + (warranties != null ? warranties.size() : 0) + " items");
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Xóa tất cả các hàng hiện có
        
        if (warranties == null || warranties.isEmpty()) {
            System.out.println("No warranties to display");
            return;
        }
        
        // Định dạng ngày tháng
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        
        // Thêm dữ liệu từ danh sách bảo hành
        for (Warranty warranty : warranties) {
            try {
                System.out.println("Adding warranty: ID=" + warranty.getWarrantyId());
                
                String startDateStr = warranty.getStartDate() != null ? 
                    warranty.getStartDate().format(formatter) : "";
                    
                model.addRow(new Object[]{
                    warranty.getWarrantyId(),
                    startDateStr,
                    warranty.getCustomerId(),
                    warranty.getCustomerName(),
                    warranty.getCustomerPhone(),
                    warranty.getProductName(),
                    warranty.getProductId(),
                    warranty.isUsed() ? "Đã sử dụng" : "Chưa sử dụng"
                });
            } catch (Exception e) {
                System.err.println("Error adding warranty to table: " + e.getMessage());
                e.printStackTrace();
            }
        }
        
        System.out.println("Table updated with " + model.getRowCount() + " rows");
    }

    /**
     * Xóa tất cả dữ liệu trong bảng
     */
    public void clearWarrantyTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
    }

    /**
     * Trả về bảng hiển thị danh sách bảo hành
     * @return Bảng bảo hành
     */
    public JTable getWarrantyTable() {
        return jTable1;
    }

    /**
     * Trả về trường nhập từ khóa tìm kiếm
     * @return Trường tìm kiếm
     */
    public JTextField getSearchField() {
        return jTextField1;
    }

    /**
     * Test trực tiếp tải dữ liệu từ service
     */
    private void testDirectServiceCall() {
        try {
            WarrantyService service = ServiceFactory.getWarrantyService();
            List<Warranty> warranties = service.getAllWarranties();
            System.out.println("Direct service call: Found " + warranties.size() + " warranties");
            updateWarrantyTable(warranties);
        } catch (Exception e) {
            System.err.println("Direct service call failed: " + e.getMessage());
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnDetailWarrantyCard;
    private com.k33ptoo.components.KButton btnWarrantyInformationLookup;
    private com.k33ptoo.components.KButton btnWarrantyRegistration;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
