/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pcstore.view;

import java.awt.Component;

/**
 *
 * @author DUC ANH
 */
public class WarrantyServiceHomeForm extends javax.swing.JPanel {

    private Component returnServicePanel;
    private WarrantyServiceForm warrantyServicePanel;
    private RepairServiceForm repairServicePanel;

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private com.k33ptoo.components.KButton btnDetailWarrantyCard;
     private com.k33ptoo.components.KButton btnWarrantyInformationLookup;
     private com.k33ptoo.components.KButton btnWarrantyRegistration;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JPanel jPanel2;
     private javax.swing.JPanel jPanel3;
     private javax.swing.JPanel jPanel4;
     private javax.swing.JPanel jPanel5;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JTable jTable1;
     private javax.swing.JTextField jTextField1;
     private javax.swing.JTextField jTextField2;
     private com.k33ptoo.components.KGradientPanel kGradientPanel1;
     private javax.swing.JLabel lbRepairService;
     private javax.swing.JLabel lbReturnService;
     private javax.swing.JLabel lbWarrantyService;
     // End of variables declaration//GEN-END:variables

    /**
     * Creates new form WarrantyService1
     */
    
    public WarrantyServiceHomeForm() {
        initComponents();
        
        returnServicePanel = new ReturnServiceForm();
        warrantyServicePanel = new WarrantyServiceForm();
        repairServicePanel = new RepairServiceForm();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        lbWarrantyService = new javax.swing.JLabel();
        lbReturnService = new javax.swing.JLabel();
        lbRepairService = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnWarrantyInformationLookup = new com.k33ptoo.components.KButton();
        jTextField1 = new javax.swing.JTextField();
        btnWarrantyRegistration = new com.k33ptoo.components.KButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnDetailWarrantyCard = new com.k33ptoo.components.KButton();

        jTextField2.setText("jTextField2");

        java.util.ResourceBundle bundle = com.pcstore.utils.LocaleManager.getInstance().getResourceBundle(); // NOI18N
        kGradientPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("pnService"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        kGradientPanel1.setkFillBackground(false);
        kGradientPanel1.setMaximumSize(new java.awt.Dimension(1153, 713));
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(1153, 713));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1153, 713));
        kGradientPanel1.setLayout(new javax.swing.BoxLayout(kGradientPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 10));

        lbWarrantyService.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbWarrantyService.setText(bundle.getString("WarrantyServiceW")); // NOI18N
        lbWarrantyService.setMaximumSize(new java.awt.Dimension(119, 40));
        lbWarrantyService.setMinimumSize(new java.awt.Dimension(119, 40));
        lbWarrantyService.setPreferredSize(new java.awt.Dimension(130, 30));
        lbWarrantyService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbWarrantyServiceMouseClicked(evt);
            }
        });
        jPanel1.add(lbWarrantyService);

        lbReturnService.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbReturnService.setText(bundle.getString("ReTurnService")); // NOI18N
        lbReturnService.setPreferredSize(new java.awt.Dimension(150, 30));
        lbReturnService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReturnServiceMouseClicked(evt);
            }
        });
        jPanel1.add(lbReturnService);

        lbRepairService.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbRepairService.setText(bundle.getString("RepairService")); // NOI18N
        lbRepairService.setPreferredSize(new java.awt.Dimension(130, 30));
        lbRepairService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbRepairServiceMouseClicked(evt);
            }
        });
        jPanel1.add(lbRepairService);

        kGradientPanel1.add(jPanel1);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 250, 5));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm Kiếm"));
        jPanel3.setPreferredSize(new java.awt.Dimension(425, 65));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnWarrantyInformationLookup.setText(bundle.getString("btnWarrantyInformationLookup")); // NOI18N
        btnWarrantyInformationLookup.setkBackGroundColor(new java.awt.Color(102, 153, 255));
        btnWarrantyInformationLookup.setkEndColor(new java.awt.Color(102, 153, 255));
        btnWarrantyInformationLookup.setkHoverEndColor(new java.awt.Color(102, 153, 255));
        btnWarrantyInformationLookup.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnWarrantyInformationLookup.setkHoverStartColor(new java.awt.Color(153, 255, 153));
        btnWarrantyInformationLookup.setkStartColor(new java.awt.Color(102, 153, 255));
        btnWarrantyInformationLookup.setMargin(new java.awt.Insets(2, 14, 0, 14));
        jPanel3.add(btnWarrantyInformationLookup, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 105, 32));

        jTextField1.setMargin(new java.awt.Insets(2, 6, 2, 0));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 292, 30));

        jPanel2.add(jPanel3);

        btnWarrantyRegistration.setText(bundle.getString("btnWarrantyRegistration")); // NOI18N
        btnWarrantyRegistration.setkEndColor(new java.awt.Color(102, 153, 255));
        btnWarrantyRegistration.setkHoverEndColor(new java.awt.Color(102, 153, 255));
        btnWarrantyRegistration.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnWarrantyRegistration.setkHoverStartColor(new java.awt.Color(153, 255, 153));
        btnWarrantyRegistration.setkStartColor(new java.awt.Color(102, 153, 255));
        btnWarrantyRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWarrantyRegistrationMouseClicked(evt);
            }
        });
        jPanel2.add(btnWarrantyRegistration);

        jPanel5.add(jPanel2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Bảo Hành ", "Ngày Yêu Cầu", "Mã Khách Hàng", "Tên Khách Hàng", "Số Điện Thoại", "Tên sản Phẩm ", "Mã Sản Phẩm", "Tình Trạng"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 20));

        btnDetailWarrantyCard.setText(bundle.getString("btnDetailWarrantyCard")); // NOI18N
        btnDetailWarrantyCard.setkEndColor(new java.awt.Color(102, 153, 255));
        btnDetailWarrantyCard.setkHoverEndColor(new java.awt.Color(102, 153, 255));
        btnDetailWarrantyCard.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDetailWarrantyCard.setkHoverStartColor(new java.awt.Color(153, 255, 153));
        btnDetailWarrantyCard.setkStartColor(new java.awt.Color(102, 153, 255));
        jPanel4.add(btnDetailWarrantyCard);

        jPanel5.add(jPanel4);

        kGradientPanel1.add(jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1121, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private void lbReturnServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReturnServiceMouseClicked
       jPanel5.removeAll();

       // Thêm ReturnServiceForm panel vào jPanel1
       jPanel5.setLayout(new java.awt.BorderLayout());
       jPanel5.add(returnServicePanel, java.awt.BorderLayout.CENTER);
   
       // Cập nhật giao diện
       jPanel5.repaint();
       jPanel5.revalidate();
    }//GEN-LAST:event_lbReturnServiceMouseClicked

    private void lbWarrantyServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbWarrantyServiceMouseClicked
        jPanel5.removeAll();

       // Thêm ReturnServiceForm panel vào jPanel1
       jPanel5.setLayout(new java.awt.BorderLayout());
       jPanel5.add(warrantyServicePanel, java.awt.BorderLayout.CENTER);
   
       // Cập nhật giao diện
       jPanel5.repaint();
       jPanel5.revalidate();
    }//GEN-LAST:event_lbWarrantyServiceMouseClicked

    private void lbRepairServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRepairServiceMouseClicked
      jPanel5.removeAll();

       // Thêm ReturnServiceForm panel vào jPanel1
       jPanel5.setLayout(new java.awt.BorderLayout());
       jPanel5.add(repairServicePanel, java.awt.BorderLayout.CENTER);
   
       // Cập nhật giao diện
       jPanel5.repaint();
       jPanel5.revalidate();
    }//GEN-LAST:event_lbRepairServiceMouseClicked

    private void btnWarrantyRegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWarrantyRegistrationMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWarrantyRegistrationMouseClicked


   
}
