/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pcstore.utils;

import java.util.ResourceBundle;

import javax.swing.JTextField;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatPropertiesLaf;

/**
 *
 * @author MSII
 */
public class TextFieldSearch extends javax.swing.JPanel {

    /**
     * Creates new form TextFieldSearch
     */
    public TextFieldSearch() {
        initComponents();
        setPlaceHolder();
    }

    private static void placeHolder(JTextField textField, String text) {
        textField.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, text);
        // Placeholder        
    }
    
    private void setPlaceHolder(){
        ResourceBundle bundle = ResourceBundle.getBundle("com.pcstore.resources.vi_VN");
        placeHolder(txtSearchField, bundle.getString("txtSearchField"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kPanelFieldSearch = new com.k33ptoo.components.KGradientPanel();
        txtSearchField = new javax.swing.JTextField();
        btnSearch = new com.k33ptoo.components.KButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        kPanelFieldSearch.setBackground(new java.awt.Color(255, 255, 255));
        kPanelFieldSearch.setkEndColor(new java.awt.Color(255, 255, 255));
        kPanelFieldSearch.setkStartColor(new java.awt.Color(255, 255, 255));
        kPanelFieldSearch.setOpaque(false);

        txtSearchField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtSearchField.setToolTipText("");
        txtSearchField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 51, 51)));
        txtSearchField.setOpaque(true);
        txtSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kPanelFieldSearchLayout = new javax.swing.GroupLayout(kPanelFieldSearch);
        kPanelFieldSearch.setLayout(kPanelFieldSearchLayout);
        kPanelFieldSearchLayout.setHorizontalGroup(
            kPanelFieldSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kPanelFieldSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchField, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addContainerGap())
        );
        kPanelFieldSearchLayout.setVerticalGroup(
            kPanelFieldSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSearchField, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pcstore/resources/icon/search.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/pcstore/resources/vi_VN"); // NOI18N
        btnSearch.setText(bundle.getString("btnSearch")); // NOI18N
        btnSearch.setToolTipText("");
        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnSearch.setIconTextGap(15);
        btnSearch.setkBorderRadius(30);
        btnSearch.setkEndColor(new java.awt.Color(153, 255, 153));
        btnSearch.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnSearch.setkHoverStartColor(new java.awt.Color(0, 153, 153));
        btnSearch.setkStartColor(new java.awt.Color(102, 153, 255));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kPanelFieldSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(kPanelFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchFieldActionPerformed
        // TODO add your handling code here:
        System.out.println(txtSearchField.getText());

    }//GEN-LAST:event_txtSearchFieldActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * Lấy text từ trường tìm kiếm
     * @return Nội dung text tìm kiếm
     */
    public String getText() {
        return txtSearchField.getText();
    }

    /**
     * Thiết lập text cho trường tìm kiếm
     * @param text Text cần thiết lập
     */
    public void setText(String text) {
        txtSearchField.setText(text);
    }

    /**
     * Lấy document của trường tìm kiếm để thêm DocumentListener
     * @return Document của trường tìm kiếm
     */
    public javax.swing.text.Document getDocument() {
        return txtSearchField.getDocument();
    }

    public JTextField getTxtSearchField() {
        return txtSearchField;
    }
    public void setTxtSearchField(JTextField txtSearchField) {
        this.txtSearchField = txtSearchField;
    }
    public com.k33ptoo.components.KButton getBtnSearch() {
        return btnSearch;
    }
    public void setBtnSearch(com.k33ptoo.components.KButton btnSearch) {
        this.btnSearch = btnSearch;
    }
    public com.k33ptoo.components.KGradientPanel getkPanelFieldSearch() {
        return kPanelFieldSearch;
    }
    public void setkPanelFieldSearch(com.k33ptoo.components.KGradientPanel kPanelFieldSearch) {
        this.kPanelFieldSearch = kPanelFieldSearch;
    }
    
//    public void setPlaceHolder(String text) {
//        placeHolder(txtSearchField, text);
//    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnSearch;
    private com.k33ptoo.components.KGradientPanel kPanelFieldSearch;
    private javax.swing.JTextField txtSearchField;
    // End of variables declaration//GEN-END:variables
}
